BEGIN;
INSERT INTO auth.users(id,email) VALUES ('55555555-5555-4555-8555-555555555551','loads-a@example.invalid'),('55555555-5555-4555-8555-555555555552','loads-b@example.invalid');
SET LOCAL ROLE authenticated;
SELECT set_config('request.jwt.claim.sub','55555555-5555-4555-8555-555555555551',true);
DO $$
DECLARE company uuid; other_company uuid; client uuid; kind uuid; contract uuid; farm_a uuid; farm_b uuid; plot_a uuid; plot_b uuid; load uuid; r jsonb; base jsonb; input jsonb;
 details jsonb:='{"tradeName":"","cnpj":"","street":"","number":"","complement":"","district":"","city":"","state":"","zipCode":"","phone":"","email":""}';
BEGIN
 r=public.billing_rpc('companies','save',details||'{"legalName":"Empresa de carregamentos","isPrimary":true}');company=(r->>'id')::uuid;
 r=public.billing_rpc('companies','save',details||'{"legalName":"Outra empresa","isPrimary":false}');other_company=(r->>'id')::uuid;
 r=public.billing_rpc('clients','save',details||'{"legalName":"Usina teste","cnpj":"11222333000181"}');client=(r->'client'->>'id')::uuid;
 r=public.billing_rpc('contract-types','save','{"name":"Carregamentos","stages":[{"id":"load","name":"Carregamento"}]}');
 r=public.billing_rpc('contract-types','list');kind=(r->'types'->0->>'id')::uuid;
 r=public.billing_rpc('contracts','save',jsonb_build_object('companyId',company,'clientId',client,'typeId',kind,'title','Contrato teste','status','Ativo','startDate','2026-01-01','contractedVolume','200'));
 contract=(r->'contract'->>'id')::uuid;
 r=public.billing_rpc('farms','save','{"name":"Fazenda Aurora","areaHa":"10","city":"Itabaiana","state":"SE"}');farm_a=(r->'farm'->>'id')::uuid;
 r=public.billing_rpc('plots','save',jsonb_build_object('farmId',farm_a,'name','Talhão Norte','areaHa','10'));plot_a=(r->'data'->'plots'->0->>'id')::uuid;
 r=public.billing_rpc('farms','save','{"name":"Fazenda Bela Vista","areaHa":"10","city":"Itabaiana","state":"SE"}');farm_b=(r->'farm'->>'id')::uuid;
 r=public.billing_rpc('plots','save',jsonb_build_object('farmId',farm_b,'name','Talhão Sul','areaHa','10'));plot_b=(r->'data'->'plots'->0->>'id')::uuid;
 PERFORM public.billing_rpc('atr','save','{"year":2025,"month":12,"monthlyGrossValue":"80","monthlyNetValue":"70","accumulatedGrossValue":"60","accumulatedNetValue":"50"}');
 PERFORM public.billing_rpc('atr','save','{"year":2026,"month":1,"monthlyGrossValue":"160","monthlyNetValue":"150","accumulatedGrossValue":"140","accumulatedNetValue":"130"}');
 PERFORM public.billing_rpc('atr','save','{"year":2026,"month":2,"monthlyGrossValue":"120","monthlyNetValue":"110","accumulatedGrossValue":"100","accumulatedNetValue":"90"}');
 base=jsonb_build_object('companyId',company,'contractId',contract);
 input=base||jsonb_build_object('farmId',farm_a,'plotId',plot_a,'loadedAt','2026-01-31','volume','10,125','atr','80','document','ROM%01','notes','Especial');
 r=public.billing_rpc('contracts','save-load',input);load=(r->'load'->>'id')::uuid;
 PERFORM public.billing_rpc('contracts','save-load',input||jsonb_build_object('loadedAt','2026-02-01','volume','20','atr','100','document','ROM-02','notes',''));
 PERFORM public.billing_rpc('contracts','save-load',input||jsonb_build_object('farmId',farm_b,'plotId',plot_b,'loadedAt','2026-02-28','volume','30','atr','200','document','ROM-03','notes',''));
 PERFORM public.billing_rpc('contracts','save-load',input||jsonb_build_object('farmId',farm_b,'plotId',plot_b,'loadedAt','2026-03-01','volume','39.875','atr','120','document','ROM-04','notes',''));
 base=base||'{"view":"loads"}'::jsonb;
 r=public.billing_rpc('contracts','list',base);
 IF r->'summary'->>'volume'<>'100' OR r->'summary'->>'averageAtr'<>'135.95' OR (r->'summary'->>'loadCount')::int<>4 OR (r->'summary'->>'farmCount')::int<>2 OR (r->'summary'->>'plotCount')::int<>2 OR jsonb_array_length(r->'groups')<>3 OR r->'groups'->0->>'label'<>'2026-03' THEN RAISE EXCEPTION 'Load snapshot totals, weighted ATR or month ordering incorrect: %',r; END IF;
 r=public.billing_rpc('contracts','list',base||'{"from":"2026-02-01","to":"2026-02-28"}');
 IF r->'summary'->>'volume'<>'50' OR r->'summary'->>'averageAtr'<>'160' OR jsonb_array_length(r->'groups'->0->'loads')<>2 OR r->'groups'->0->>'volume'<>'50' THEN RAISE EXCEPTION 'Inclusive period must filter records, KPIs and groups together'; END IF;
 r=public.billing_rpc('contracts','list',base||'{"search":"aUrOrA","groupBy":"farm"}');
 IF r->'summary'->>'volume'<>'30.125' OR r->'groups'->0->>'label'<>'Fazenda Aurora' OR (r->'summary'->>'farmCount')::int<>1 THEN RAISE EXCEPTION 'Case-insensitive farm search failed'; END IF;
 r=public.billing_rpc('contracts','list',base||'{"search":"Sul","from":"2026-02-01","to":"2026-02-28","groupBy":"none"}');
 IF r->'summary'->>'volume'<>'30' OR r->'groups'->0->>'key'<>'all' THEN RAISE EXCEPTION 'Combined plot/date filters or flat view failed'; END IF;
 r=public.billing_rpc('contracts','list',base||'{"search":"%"}');
 IF r->'summary'->>'volume'<>'10.125' THEN RAISE EXCEPTION 'Search wildcards must be literal'; END IF;
 r=public.billing_rpc('contracts','list',base||'{"search":"especial"}');
 IF r->'summary'->>'volume'<>'10.125' THEN RAISE EXCEPTION 'Notes search failed'; END IF;
 r=public.billing_rpc('contracts','list',base||'{"to":"2025-12-31"}');
 IF r->'summary'->>'volume'<>'0' OR r->'summary'->>'averageAtr'<>'' OR r->'groups'<>'[]' OR (r->'summary'->>'farmCount')::int<>0 THEN RAISE EXCEPTION 'Empty snapshot contains stale metrics'; END IF;
 BEGIN PERFORM public.billing_rpc('contracts','list',base||'{"from":"2026-03-01","to":"2026-02-28"}');RAISE EXCEPTION 'Reversed period accepted';EXCEPTION WHEN invalid_parameter_value THEN NULL;END;
 BEGIN PERFORM public.billing_rpc('contracts','list',base||'{"from":"2026-02-30"}');RAISE EXCEPTION 'Invalid date accepted';EXCEPTION WHEN invalid_parameter_value THEN NULL;END;
 BEGIN PERFORM public.billing_rpc('contracts','list',base||'{"groupBy":"invalid"}');RAISE EXCEPTION 'Invalid grouping accepted';EXCEPTION WHEN invalid_parameter_value THEN NULL;END;
 BEGIN PERFORM public.billing_rpc('contracts','list',base||'{"ownerId":"55555555-5555-4555-8555-555555555552"}');RAISE EXCEPTION 'Owner injection accepted';EXCEPTION WHEN invalid_parameter_value THEN NULL;END;
 BEGIN PERFORM public.billing_rpc('contracts','list',base||jsonb_build_object('companyId',other_company));RAISE EXCEPTION 'Cross-company load query accepted';EXCEPTION WHEN no_data_found THEN NULL;END;
 BEGIN PERFORM public.billing_rpc('contracts','save-load',input||jsonb_build_object('farmId',farm_b,'plotId',plot_a));RAISE EXCEPTION 'Cross-farm plot accepted';EXCEPTION WHEN invalid_parameter_value THEN NULL;END;
 BEGIN PERFORM public.billing_rpc('contracts','save-load',input||'{"loadedVolume":"0"}');RAISE EXCEPTION 'Client business total accepted';EXCEPTION WHEN invalid_parameter_value THEN NULL;END;
 r=public.billing_rpc('contracts','save-load',input||jsonb_build_object('id',load,'volume','11.125'));
 r=public.billing_rpc('contracts','list',base);IF r->'summary'->>'volume'<>'101' THEN RAISE EXCEPTION 'Edit did not refresh snapshot';END IF;
 PERFORM public.billing_rpc('contracts','delete-load',jsonb_build_object('companyId',company,'contractId',contract,'id',load));
 r=public.billing_rpc('contracts','list',base);IF r->'summary'->>'volume'<>'89.875' THEN RAISE EXCEPTION 'Delete did not refresh snapshot';END IF;
 PERFORM set_config('request.jwt.claim.sub','55555555-5555-4555-8555-555555555552',true);
 BEGIN PERFORM public.billing_rpc('contracts','list',base);RAISE EXCEPTION 'Other owner can read loads';EXCEPTION WHEN no_data_found THEN NULL;END;
 PERFORM set_config('request.jwt.claim.sub','',true);
 BEGIN PERFORM public.billing_rpc('contracts','list',base);RAISE EXCEPTION 'Missing session accepted';EXCEPTION WHEN invalid_authorization_specification THEN NULL;END;
END $$;
ROLLBACK;
