import {drawReportPdfHeader,drawReportPdfWatermark,formatReportCnpj,REPORT_MARGIN_MM,type ReportPdfBrand,type ReportPdfImage} from '@/shared/reporting';
import {loadReportImage} from '@/shared/reporting/loadReportImage';
import {dateLabel,moneyLabel} from '@/shared/utils/presentation';
import type {jsPDF as JsPdf} from 'jspdf';
import type {PurchaseOrder} from '../types';

export type PurchaseOrderSnapshot=PurchaseOrder;

export function createPurchaseOrderSnapshot(order:PurchaseOrder):PurchaseOrderSnapshot{
  return structuredClone(order);
}

const safeFilePart=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9]+/g,'-').replace(/^-|-$/g,'').toLowerCase()||'pedido';
const limitedLines=(doc:JsPdf,value:string,width:number,limit:number)=>{const lines=doc.splitTextToSize(value,width) as string[];if(lines.length<=limit)return lines;const visible=lines.slice(0,limit),last=visible[limit-1]?.replace(/[.\s]+$/,'')??'';visible[limit-1]=`${last}...`;return visible;};
function supplierDocument(order:PurchaseOrderSnapshot){const value=order.providerDocument.trim(),digits=value.replace(/\D/g,'');if(order.providerDocumentType==='CPF')return digits.length===11?digits.replace(/^(\d{3})(\d{3})(\d{3})(\d{2})$/,'$1.$2.$3-$4'):value||'Não informado';return value?formatReportCnpj(value):'Não informado';}
async function itemImages(order:PurchaseOrderSnapshot){const cache=new Map<string,ReportPdfImage|null>();const urls=[...new Set(order.items.map(item=>item.materialImageUrl).filter((url):url is string=>!!url))];for(let index=0;index<urls.length;index+=4){const batch=urls.slice(index,index+4),images=await Promise.all(batch.map(url=>loadReportImage(url).catch(()=>null)));batch.forEach((url,i)=>cache.set(url,images[i]));}return order.items.map(item=>item.materialImageUrl?cache.get(item.materialImageUrl)??null:null);}

export async function createPurchaseOrderPdf(order:PurchaseOrderSnapshot,brand:ReportPdfBrand){
  const {jsPDF}=await import('@/shared/reporting/jsPdfRuntime');
  const doc=new jsPDF({orientation:'portrait',unit:'mm',format:'a4',compress:true});
  const width=doc.internal.pageSize.getWidth(),height=doc.internal.pageSize.getHeight(),margin=REPORT_MARGIN_MM,content=width-margin*2,bottom=height-margin-9;
  const [logo,watermark,images]=await Promise.all([loadReportImage(brand.company?.logoUrl??null),loadReportImage(brand.watermark.imageUrl),itemImages(order)]);
  const addHeader=(continuation=false)=>{drawReportPdfWatermark(doc,width,height,brand.watermark,watermark);return drawReportPdfHeader({doc,pageWidth:width,margin,orientation:'portrait',settings:brand.header,company:brand.company,logo,title:continuation?'Pedido de compra · continuação':'Pedido de compra'})+6;};
  let y=addHeader();
  const pair=(label:string,value:string,x:number,w:number,top:number)=>{doc.setFont('helvetica','normal');doc.setFontSize(6.2);doc.setTextColor(120,136,125);doc.text(label.toUpperCase(),x,top);doc.setFont('helvetica','bold');doc.setFontSize(8);doc.setTextColor(48,78,57);doc.text(limitedLines(doc,value||'Não informado',w,2),x,top+4,{lineHeightFactor:1.1});};
  const drawSummary=()=>{doc.setFillColor(242,247,243);doc.roundedRect(margin,y,content,22,1.5,1.5,'F');pair('Pedido',order.number,margin+4,37,y+5);pair('Cotação',order.quotationNumber,margin+43,38,y+5);pair('Ordem de compra',order.purchaseOrderNumber||'Não informada',margin+83,51,y+5);pair('Data da cotação',dateLabel(order.requestDate),margin+136,content-140,y+5);y+=27;};
  const drawSupplier=()=>{doc.setFont('helvetica','bold');doc.setFontSize(8.5);doc.setTextColor(48,75,57);doc.text('Fornecedor',margin,y);y+=4;doc.setDrawColor(216,228,220);doc.roundedRect(margin,y,content,31,1.2,1.2);pair(order.providerDocumentType==='CPF'?'Nome':'Razão social',order.providerLegalName,margin+4,82,y+5);pair(order.providerDocumentType==='CPF'?'Nome profissional':'Nome fantasia',order.providerTradeName||'Não informado',margin+91,content-95,y+5);pair(order.providerDocumentType||'Documento',supplierDocument(order),margin+4,55,y+18);pair('Contato',[order.providerPhone,order.providerEmail].filter(Boolean).join(' · ')||'Não informado',margin+64,content-68,y+18);y+=36;};
  const drawCommercial=()=>{doc.setFillColor(231,243,235);doc.roundedRect(margin,y,content,15,1.2,1.2,'F');pair('Forma de pagamento',order.paymentMethod||'Não informada',margin+4,90,y+5);pair('Situação',order.status==='finished'?'Finalizado':'Em aberto',margin+100,40,y+5);pair('Valor total',moneyLabel(order.total),margin+144,content-148,y+5);y+=20;};
  const drawTableHeader=()=>{doc.setFillColor(226,238,230);doc.rect(margin,y,content,9,'F');doc.setFont('helvetica','bold');doc.setFontSize(6.2);doc.setTextColor(53,84,62);[['Foto',12],['Produto',35],['Qtd.',116],['Unitário',143],['Total',174]].forEach(([label,x])=>doc.text(String(label),margin+Number(x),y+5,{align:Number(x)>100?'center':'left'}));y+=9;};
  const drawImage=(image:ReportPdfImage,x:number,top:number,w:number,h:number)=>{let iw=w,ih=iw/image.ratio;if(ih>h){ih=h;iw=ih*image.ratio;}doc.addImage(image.bytes,image.format,x+(w-iw)/2,top+(h-ih)/2,iw,ih,undefined,'FAST');};
  const newPage=()=>{doc.addPage();y=addHeader(true);drawTableHeader();};
  drawSummary();drawSupplier();drawCommercial();
  doc.setFont('helvetica','bold');doc.setFontSize(8.5);doc.setTextColor(48,75,57);doc.text(`Itens do pedido (${order.itemCount})`,margin,y);y+=4;drawTableHeader();
  order.items.forEach((item,index)=>{const row=26;if(y+row+(index===order.items.length-1?20:0)>bottom)newPage();const top=y;if(index%2===0){doc.setFillColor(249,251,249);doc.rect(margin,top,content,row,'F');}doc.setFillColor(243,247,244);doc.roundedRect(margin+2,top+2,21,row-4,1,1,'F');if(images[index])drawImage(images[index]!,margin+2.7,top+2.7,19.6,row-5.4);else{doc.setFont('helvetica','normal');doc.setFontSize(5);doc.setTextColor(150,163,154);doc.text('SEM FOTO',margin+12.5,top+14,{align:'center'});}doc.setFont('helvetica','bold');doc.setFontSize(7.4);doc.setTextColor(43,70,51);doc.text(limitedLines(doc,item.materialName,75,2),margin+27,top+5,{lineHeightFactor:1.1});const detail=[item.materialInternalCode&&`Cód.: ${item.materialInternalCode}`,item.materialReferences.map(reference=>[reference.brand,reference.code].filter(Boolean).join(' ')).filter(Boolean).join(' · '),item.notes].filter(Boolean).join(' · ');doc.setFont('helvetica','normal');doc.setFontSize(5.8);doc.setTextColor(100,118,106);if(detail)doc.text(limitedLines(doc,detail,75,3),margin+27,top+13,{lineHeightFactor:1.1});doc.setFontSize(6.8);doc.setTextColor(48,78,57);doc.text(`${item.quantity} ${item.unit}`,margin+116,top+14,{align:'center'});doc.text(moneyLabel(item.unitPrice),margin+143,top+14,{align:'center'});doc.setFont('helvetica','bold');doc.text(moneyLabel(item.lineTotal),width-margin-3,top+14,{align:'right'});doc.setDrawColor(220,229,223);doc.rect(margin,top,content,row);y+=row;});
  if(y+18>bottom)newPage();y+=5;doc.setFillColor(222,239,227);doc.roundedRect(width-margin-74,y,74,14,1.2,1.2,'F');doc.setFont('helvetica','normal');doc.setFontSize(7);doc.setTextColor(91,112,98);doc.text('TOTAL DO PEDIDO',width-margin-70,y+5);doc.setFont('helvetica','bold');doc.setFontSize(11);doc.setTextColor(33,105,62);doc.text(moneyLabel(order.total),width-margin-4,y+10.5,{align:'right'});
  const pages=doc.getNumberOfPages(),issued=new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(brand.issuedAt);for(let page=1;page<=pages;page++){doc.setPage(page);doc.setDrawColor(232,237,233);doc.line(margin,height-margin-3,width-margin,height-margin-3);doc.setFont('helvetica','normal');doc.setFontSize(6.5);doc.setTextColor(131,147,137);doc.text(`Emitido por ${brand.issuer.name} · ${issued}`,margin,height-margin);doc.text(`${page} / ${pages}`,width-margin,height-margin,{align:'right'});}
  return {doc,fileName:`pedido-${safeFilePart(order.number)}-${safeFilePart(order.providerLegalName)}.pdf`};
}
