import Link from 'next/link';
import {useState,useRef,useEffect} from 'react';
import {Sprout,Leaf,Plus,Pencil,ChevronRight,ArrowLeft,ArrowUpRight,Loader2,RefreshCw} from 'lucide-react';
import {ModuleLink,useModuleNavigation} from '@/shared/navigation/ModuleNavigation';
import {notifications} from '@/shared/feedback';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {useCultures} from '../hooks/useCultures';
import {CultureForm} from '../forms/CultureForm';
import {culturesHref,cultureHref} from '../utils/cultureNavigation';
type Draft={kind:'culture'|'subtype';id?:string;name?:string;cultureId?:string};
export function CulturasPage(){
 const mounted=useRef(true);useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);const m=useCultures();const {searchParams,navigate}=useModuleNavigation();const selectedId=searchParams.get('cultura');const culture=m.cultures.find(c=>c.id===selectedId);const [draft,setDraft]=useState<Draft>({kind:'culture'});const [open,setOpen]=useState(false);const [busy,setBusy]=useState(false);
 const begin=(value:Draft)=>{setDraft(value);setBusy(false);setOpen(true);};
 return <section><div className="client-navigation"><nav className="client-breadcrumb" aria-label="Caminho de navegação"><ModuleLink href="/cadastro">Cadastros</ModuleLink><ChevronRight size={13}/>{selectedId?<><ModuleLink href={culturesHref}>Culturas</ModuleLink><ChevronRight size={13}/><span aria-current="page">{culture?.name||'Cultura'}</span></>:<span aria-current="page">Culturas</span>}</nav>{selectedId&&<ModuleLink className="client-back" href={culturesHref}><ArrowLeft size={15}/>Voltar às culturas</ModuleLink>}</div>
 <div className="companies-heading"><div><h2>{culture?.name||'Culturas'}</h2><p>{culture?'Cadastre os subtipos desta cultura.':'Cadastre as culturas principais e organize seus subtipos.'}</p></div>{!m.loading&&!m.error&&(!selectedId||culture)&&<div className="culture-heading-actions">{culture&&<button className="btn" onClick={()=>begin({kind:'culture',id:culture.id,name:culture.name})}><Pencil size={15}/>Editar nome</button>}<button className="btn company-primary" onClick={()=>begin(culture?{kind:'subtype',cultureId:culture.id}:{kind:'culture'})}><Plus size={16}/>{culture?'Cadastrar subtipo':'Cadastrar cultura'}</button></div>}</div>
 {m.loading?<div className="client-loading" role="status"><Loader2 className="animate-spin" size={20}/>Carregando culturas…</div>:m.error?<div className="company-empty" role="alert"><h3>{m.status===401?'Acesse suas culturas':'Não foi possível carregar'}</h3><p>{m.error}</p>{m.status===401?<Link className="btn company-primary" href="/login?returnTo=%2Fcadastro%3Fsecao%3Dculturas" target="_top">Entrar</Link>:<button className="btn" onClick={m.reload}><RefreshCw size={16}/>Tentar novamente</button>}</div>:selectedId&&!culture?<div className="company-empty"><h3>Cultura não encontrada</h3><p>Volte à lista para selecionar uma cultura cadastrada.</p></div>:culture?<>{!culture.subtypes.length?<div className="company-empty"><span className="company-empty-icon"><Leaf size={25}/></span><h3>Adicione os subtipos de {culture.name}</h3><p>Cada subtipo ficará vinculado a esta cultura.</p><button className="btn company-primary" onClick={()=>begin({kind:'subtype',cultureId:culture.id})}><Plus size={16}/>Cadastrar subtipo</button></div>:<div className="farm-grid">{culture.subtypes.map(sub=><button key={sub.id} className="farm-card culture-card" onClick={()=>begin({kind:'subtype',cultureId:culture.id,id:sub.id,name:sub.name})} aria-label={'Editar '+sub.name}><span className="farm-card-top"><span className="farm-card-icon"><Leaf size={20}/></span><Pencil size={14}/></span><span className="farm-card-name">{sub.name}</span><span className="farm-card-location">{culture.name}</span></button>)}</div>}</>:!m.cultures.length?<div className="company-empty"><span className="company-empty-icon"><Sprout size={25}/></span><h3>Cadastre sua primeira cultura</h3><p>Por exemplo: cadastre Cana e, dentro dela, Cana soca e Cana planta.</p><button className="btn company-primary" onClick={()=>begin({kind:'culture'})}><Plus size={16}/>Cadastrar cultura</button></div>:<div className="farm-grid">{m.cultures.map(c=><ModuleLink key={c.id} href={cultureHref(c.id)} className="farm-card culture-card"><span className="farm-card-top"><span className="farm-card-icon"><Sprout size={20}/></span><ArrowUpRight size={16}/></span><h3 className="farm-card-name">{c.name}</h3><span className="farm-card-location">{c.subtypes.length} subtipo{c.subtypes.length!==1?'s':''}</span></ModuleLink>)}</div>}
 <Dialog open={open} onOpenChange={value=>{if(!busy)setOpen(value);}}><DialogContent className="form-modal farm-modal" onEscapeKeyDown={event=>{if(busy)event.preventDefault();}} onPointerDownOutside={event=>{if(busy)event.preventDefault();}}><DialogHeader><DialogTitle>{draft.id?'Editar ': 'Cadastrar '}{draft.kind==='subtype'?'subtipo':'cultura'}</DialogTitle><DialogDescription>{draft.kind==='subtype'?m.cultures.find(c=>c.id===draft.cultureId)?.name:'Informe a cultura principal.'}</DialogDescription></DialogHeader><CultureForm name={draft.name} subtype={draft.kind==='subtype'} onBusy={setBusy} onClose={()=>{setBusy(false);setOpen(false);}} onSave={async name=>{const id=await m.save({...draft,name});if(mounted.current){if(draft.id)notifications.updated('O cadastro foi atualizado.');else notifications.created('O cadastro foi concluído.');if(draft.kind==='culture'&&!draft.id)navigate(cultureHref(id));}}}/></DialogContent></Dialog>
 </section>;
}
