import Link from 'next/link';
import {Plus,FileText,ArrowUpRight,ListOrdered,Loader2,RefreshCw,Check} from 'lucide-react';
import {ModuleLink} from '@/shared/navigation/ModuleNavigation';
import {useContractTypes} from '../hooks/useContractTypes';
import {contractTypesHref,contractTypeHref} from '../utils/typeNavigation';
import {ContractTypeForm} from '../forms/ContractTypeForm';
import {TypeBreadcrumb} from './TypeBreadcrumb';
function LoadState({loading,status,error,onRetry}:{loading:boolean;status:number;error:string;onRetry:()=>void}){if(loading)return <div className="client-loading" role="status"><Loader2 size={20} className="animate-spin"/>Carregando tipos…</div>;return <div className="company-empty" role="alert"><h3>{status===401?'Acesse seus tipos de contrato':status===404?'Tipo não encontrado':'Não foi possível carregar'}</h3><p>{error}</p>{status===401?<Link className="btn company-primary" href="/login?returnTo=%2Fcadastro%3Fsecao%3Dcontratos" target="_top">Entrar</Link>:status!==404&&<button className="btn" onClick={onRetry}><RefreshCw size={16}/>Tentar novamente</button>}</div>;}
export function ContractTypesList(){const m=useContractTypes();return <section><TypeBreadcrumb/><div className="companies-heading"><div><h2>Tipos de contrato</h2><p>Cada tipo possui suas próprias etapas.</p></div>{m.status!==401&&<ModuleLink className="btn company-primary" href={contractTypesHref+'&novo=1'}><Plus size={16}/>Novo tipo</ModuleLink>}</div>
  {m.loading||m.error?<LoadState {...m} onRetry={m.reload}/>:!m.types.length?<div className="company-empty"><span className="company-empty-icon"><FileText size={25}/></span><h3>Cadastre os tipos de contrato</h3><p>Comece pelo contrato manual ou semimecanizado e defina as etapas de cada um.</p><div className="contract-type-suggestions"><ModuleLink href={contractTypesHref+'&novo=manual'} className="btn">Contrato manual<Plus size={15}/></ModuleLink><ModuleLink href={contractTypesHref+'&novo=semimecanizado'} className="btn">Contrato semimecanizado<Plus size={15}/></ModuleLink></div></div>:<div className="farm-grid">{m.types.map(type=><ModuleLink className="farm-card contract-type-card" key={type.id} href={contractTypeHref(type.id)}><span className="farm-card-top"><span className="farm-card-icon"><FileText size={20}/></span><ArrowUpRight size={16}/></span><h3 className="farm-card-name" title={type.name}>{type.name}</h3><span className="farm-card-location"><ListOrdered size={15}/>{type.stages.length} etapa{type.stages.length!==1?'s':''}</span></ModuleLink>)}</div>}
</section>;}
export function ContractTypeEditor({id,saved}:{id:string;saved:boolean}){const m=useContractTypes(id);return <section><TypeBreadcrumb name={m.type?.name||'Tipo de contrato'}/>{m.loading||m.error||!m.type?<LoadState {...m} onRetry={m.reload}/>:<><div className="companies-heading"><div><h2>{m.type.name}</h2><p>Configure o nome e as etapas deste tipo.</p></div></div>{saved&&<p className="company-saved" role="status"><Check size={16}/>Tipo de contrato salvo.</p>}<ContractTypeForm type={m.type}/></>}</section>;}
