import assert from 'node:assert/strict';
import {readFileSync,readdirSync,mkdirSync} from 'node:fs';
import {createRequire} from 'node:module';
import {DatabaseSync} from 'node:sqlite';
const require=createRequire(import.meta.url);const {build}=require(require.resolve('esbuild',{paths:[require.resolve('vite')]}));
mkdirSync('.sites-runtime/tests',{recursive:true});
const plugins=[{name:'fixtures',setup(b){b.onResolve({filter:/^(cloudflare:workers|next\/headers|next\/navigation)$/},a=>({path:a.path,namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},a=>({contents:a.path==='cloudflare:workers'?'export const env=globalThis.atrTestEnv;':a.path==='next/headers'?'export async function headers(){return globalThis.atrHeaders;}':'export function redirect(){throw new Error("Unexpected redirect")}'}));}}];
await build({entryPoints:['app/api/atr/route.ts'],outfile:'.sites-runtime/tests/atr.mjs',bundle:true,platform:'node',format:'esm',plugins});
await build({entryPoints:['modules/cadastro/atr/utils/atrGrouping.ts'],outfile:'.sites-runtime/tests/atr-grouping.mjs',bundle:true,platform:'node',format:'esm'});
const sqlite=new DatabaseSync(':memory:');for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sqlite.exec(readFileSync('drizzle/'+f,'utf8'));
const DB={prepare(sql){return{bind(...args){return{async first(){return sqlite.prepare(sql).get(...args)||null;},async all(){return{results:sqlite.prepare(sql).all(...args)};},async run(){return sqlite.prepare(sql).run(...args);}};}};}};
globalThis.atrTestEnv={DB};globalThis.atrHeaders=new Headers();
const api=await import('../.sites-runtime/tests/atr.mjs');const {groupAtrByYear,formatAtrValue}=await import('../.sites-runtime/tests/atr-grouping.mjs');
const signIn=user=>{globalThis.atrHeaders=new Headers(user?{'oai-authenticated-user-id':user,'oai-authenticated-user-email':user+'@example.test'}:{});};
const base={year:2026,month:9,value:'1,123456'};
const request=(method,data,origin='https://atr.test')=>new Request('https://atr.test/api/atr',{method,headers:{'Content-Type':'application/json',origin},body:JSON.stringify(data)});
assert.equal((await api.GET()).status,401);assert.equal((await api.POST(request('POST',base))).status,401);
signIn('owner-a');let response=await api.POST(request('POST',base));assert.equal(response.status,201);const a=(await response.json()).record;assert.equal(a.value,'1.123456');assert.equal(formatAtrValue(a.value),'1,123456');assert.equal((await api.POST(request('POST',base))).status,409);
response=await api.POST(request('POST',{...base,year:2025}));assert.equal(response.status,201);const b=(await response.json()).record;
assert.equal((await api.POST(request('POST',{year:2026,month:1,value:'0'}))).status,201);
let rows=(await (await api.GET()).json()).records;assert.deepEqual(rows.map(x=>[x.year,x.month]),[[2026,1],[2026,9],[2025,9]]);let groups=groupAtrByYear([...rows].reverse());assert.deepEqual(groups.map(x=>x.year),[2026,2025]);assert.deepEqual(groups[0].records.map(x=>x.month),[9,1]);assert.equal(groups[1].records.length,1);
assert.equal((await api.PATCH(request('PATCH',{...base,id:b.id}))).status,409);rows=(await (await api.GET()).json()).records;assert.equal(rows.find(x=>x.id===b.id).year,2025);
assert.equal((await api.PATCH(request('PATCH',{...base,id:b.id,year:2024,month:12,value:'2,0500'}))).status,200);rows=(await (await api.GET()).json()).records;groups=groupAtrByYear(rows);assert.deepEqual(groups.map(x=>x.year),[2026,2024]);assert.equal(groups[1].records[0].value,'2.0500');
signIn('owner-b');assert.equal((await (await api.GET()).json()).records.length,0);assert.equal((await api.PATCH(request('PATCH',{...base,id:a.id}))).status,404);assert.equal((await api.POST(request('POST',base))).status,201);
signIn('owner-a');for(const data of [{...base,month:13},{...base,month:0},{...base,year:2026.5},{...base,value:'-2'},{...base,value:''},{...base,value:'1e5'},{...base,value:'1,1234567'}])assert.equal((await api.POST(request('POST',data))).status,400);assert.equal((await api.POST(request('POST',base,'https://other.test'))).status,403);
sqlite.close();console.log('Passed: monthly ATR persistence, annual grouping, chronological months, exact decimals, duplicate prevention, edits across years, owner isolation and validation.');
