import assert from 'node:assert/strict';
import {readFileSync,mkdirSync,readdirSync} from 'node:fs';
import {createRequire} from 'node:module';
import {DatabaseSync} from 'node:sqlite';
const require=createRequire(import.meta.url);
const {build}=require(require.resolve('esbuild',{paths:[require.resolve('vite')]}));
mkdirSync('.sites-runtime/tests',{recursive:true});
await build({entryPoints:['app/api/companies/route.ts'],outfile:'.sites-runtime/tests/companies-api.mjs',bundle:true,platform:'node',format:'esm',plugins:[{name:'local-request-fixtures',setup(builder){
 builder.onResolve({filter:/^(cloudflare:workers|next\/headers|next\/navigation)$/},args=>({path:args.path,namespace:'fixture'}));
 builder.onLoad({filter:/.*/,namespace:'fixture'},args=>({contents:args.path==='cloudflare:workers'?'export const env=globalThis.companyTestEnv;':args.path==='next/headers'?'export async function headers(){return globalThis.companyRequestHeaders;}':'export function redirect(){throw new Error("Unexpected redirect")}'}));
}}]});
const sqlite=new DatabaseSync(':memory:');
for(const migration of readdirSync('drizzle').filter(x=>x.endsWith('.sql')).sort())sqlite.exec(readFileSync('drizzle/'+migration,'utf8'));
const DB={prepare(sql){return{bind(...args){return{async first(){return sqlite.prepare(sql).get(...args)||null},async all(){return{results:sqlite.prepare(sql).all(...args)}},execute(){return sqlite.prepare(sql).run(...args)}}}}},async batch(statements){sqlite.exec('BEGIN');try{for(const statement of statements)statement.execute();sqlite.exec('COMMIT');return []}catch(e){sqlite.exec('ROLLBACK');throw e}}};
const encryptionKey=Buffer.from(crypto.getRandomValues(new Uint8Array(32))).toString('base64');
globalThis.companyTestEnv={DB,COMPANY_KEY_ENCRYPTION_KEY:encryptionKey};
globalThis.companyRequestHeaders=new Headers();
const api=await import('../.sites-runtime/tests/companies-api.mjs');
const base={legalName:'Empresa teste',tradeName:'Nome fantasia',cnpj:'12345678000199',isPrimary:true,street:'Rua Teste',number:'10',complement:'Sala 2',district:'Centro',city:'São Paulo',state:'SP',zipCode:'01001-000',phone:'11999999999',email:'contato@example.test'};
const signedIn=user=>{globalThis.companyRequestHeaders=new Headers(user?{'oai-authenticated-user-id':user,'oai-authenticated-user-email':user+'@example.test'}:{})};
const request=(method,data,origin='https://company.test')=>new Request('https://company.test/api/companies',{method,headers:{'content-type':'application/json',origin},body:JSON.stringify(data)});
assert.equal((await api.GET()).status,401);
assert.equal((await api.POST(request('POST',base))).status,401);
signedIn('owner-a');
let response=await api.POST(request('POST',base));assert.equal(response.status,201);const a=await response.json();
const listing=await (await api.GET()).json();assert.equal(listing.companies.length,1);assert.equal(listing.companies[0].legalName,base.legalName);assert.equal(listing.companies[0].name,base.tradeName);for(const k of ['street','number','complement','district','city','state','zipCode','phone','email'])assert.equal(listing.companies[0][k],base[k]);assert.ok(!JSON.stringify(listing).includes('ciphertext'));assert.ok(!('hasApiKey' in listing.companies[0]));
// Existing encrypted credentials are preserved, but no longer part of the CNPJ form or API.
sqlite.prepare('UPDATE companies SET api_key_ciphertext=? WHERE id=?').run('LEGACY_ENCRYPTED_VALUE',a.id);
signedIn('owner-b');assert.equal((await (await api.GET()).json()).companies.length,0);assert.equal((await api.PATCH(request('PATCH',{...base,id:a.id}))).status,404);
signedIn('owner-a');response=await api.POST(request('POST',{...base,legalName:'Unidade',cnpj:'98765432000199',isPrimary:false,apiKey:''}));assert.equal(response.status,201);const b=await response.json();
response=await api.PATCH(request('PATCH',{...base,id:b.id,legalName:'Nova principal',cnpj:'98765432000199',apiKey:''}));assert.equal(response.status,200);
let rows=(await (await api.GET()).json()).companies;assert.equal(rows.filter(x=>x.isPrimary).length,1);assert.equal(rows.find(x=>x.isPrimary).id,b.id);
response=await api.POST(request('POST',{...base,legalName:'CNPJ duplicado'}));assert.equal(response.status,409);rows=(await (await api.GET()).json()).companies;assert.equal(rows.find(x=>x.isPrimary).id,b.id);
assert.equal((await api.PATCH(request('PATCH',{...base,id:b.id,cnpj:'98765432000199',isPrimary:false,apiKey:''}))).status,400);
assert.equal((await api.POST(request('POST',{...base,cnpj:'123'}))).status,400);
assert.equal((await api.POST(request('POST',base,'https://other.test'))).status,403);
response=await api.PATCH(request('PATCH',{...base,id:a.id,isPrimary:false,city:'Curitiba',state:'PR'}));assert.equal(response.status,200);assert.equal(sqlite.prepare('SELECT api_key_ciphertext FROM companies WHERE id=?').get(a.id).api_key_ciphertext,'LEGACY_ENCRYPTED_VALUE');
rows=(await (await api.GET()).json()).companies;assert.equal(rows.find(x=>x.id===a.id).city,'Curitiba');assert.ok(!JSON.stringify(rows).includes('LEGACY_ENCRYPTED_VALUE'));
assert.equal((await api.POST(request('POST',{...base,cnpj:'00000000000100',email:'invalid'}))).status,400);
console.log('Passed: authentication, owner isolation, company details persistence, main/unit registration, promotion, duplicate rollback, validation, origin checks and preservation of legacy credentials.');
sqlite.close();
