import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {pathToFileURL} from 'node:url';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {build}=require(require.resolve('esbuild',{paths:[require.resolve('vite')]}));
const temporary=await mkdtemp(join(tmpdir(),'billing-config-test-'));
try{
 const output=join(temporary,'services.mjs');
 await build({stdin:{contents:`export * from './modules/configuracoes/empresas/services/companyApi'; export * from './modules/configuracoes/services/settingsService'; export * from './modules/configuracoes/marca-dagua/services/watermarkApi'; export * from './modules/configuracoes/usuarios/services/usersApi'; export * from './modules/configuracoes/perfis-acesso/services/accessProfilesApi'; export * from './modules/configuracoes/cabecalho-relatorios/services/reportHeaderApi'; export * from './shared/reporting/companyBrand';`,resolveDir:process.cwd()},outfile:output,bundle:true,platform:'node',format:'esm',plugins:[{name:'supabase-fixtures',setup(builder){
  builder.onResolve({filter:/^@\/shared\/supabase\/(rpc|client)$/},args=>({path:args.path,namespace:'fixture'}));
  builder.onLoad({filter:/.*/,namespace:'fixture'},args=>({contents:args.path.endsWith('/rpc')?'export class RpcError extends Error{constructor(message,status=400){super(message);this.status=status}};export const rpcRequest=(...args)=>globalThis.configRpc(...args);export const functionRequest=(...args)=>globalThis.configFunction(...args);':'export const getSupabaseBrowserClient=()=>globalThis.configClient;'}));
 }}]});
 const api=await import(pathToFileURL(output));
 const workspaceId='11111111-1111-4111-8111-111111111111';
 const calls=[];const uploads=[];const signs=[];const removals=[];let session={user:{id:'owner-a'},access_token:'test-session'};
 globalThis.configClient={auth:{getSession:async()=>({data:{session},error:null})},storage:{from(bucket){assert.ok(['billing-watermarks','billing-company-logos'].includes(bucket));return{upload:async(path,file,options)=>{uploads.push({bucket,path,file,options});return{error:null}},remove:async paths=>{removals.push({bucket,paths});return{error:null}},createSignedUrl:async(path,seconds)=>{signs.push({bucket,path,seconds});return{data:{signedUrl:'https://signed.example.test/'+path},error:null}},createSignedUrls:async(paths,seconds)=>{signs.push({bucket,paths,seconds});return{data:paths.map(path=>({path,signedUrl:'https://signed.example.test/'+path,error:null})),error:null}}}}}};
 globalThis.configRpc=async(resource,action,payload={},signal)=>{
  calls.push({resource,action,payload,signal});
  if(resource==='companies')return action==='list'?{companies:[{id:'company-a',logoKey:workspaceId+'/companies/existing.png',logoName:'Empresa.png'}]}:{id:'company-a',company:{id:'company-a'},previousLogoKey:workspaceId+'/companies/existing.png'};
  if(resource==='settings')return{settings:{name:payload.name??'Servidor',company:payload.company??'Espaço',compact:payload.compact??false,email:'auth@example.test',workspaceId}};
  if(resource==='users')return action==='list'?{users:[{id:'membership-a',name:'Servidor',email:'auth@example.test',status:'active',accessProfileId:null,accessProfileName:'',isOwner:true}]}:{user:{id:payload.id??'invite-a',name:'',email:payload.email??'member@example.test',status:action==='disable'?'disabled':'active',accessProfileId:payload.accessProfileId??'profile-a',accessProfileName:'Operador',isOwner:false}};
  if(resource==='access-profiles')return action==='list'?{profiles:[{id:'profile-a',name:'Operador',description:'Operação',permissions:['companies.read'],isSystem:false,userCount:0}]}:action==='delete'?{id:payload.id,deleted:true}:{profile:{id:payload.id??'profile-new',name:payload.name,description:payload.description,permissions:payload.permissions,isSystem:false,userCount:0}};
  if(resource==='report-headers')return{settings:{orientation:payload.orientation??'portrait',defaultCompanyId:payload.defaultCompanyId??null,portrait:payload.portrait??{variant:'detailed',logoAlignment:'left',showCnpj:true,showContact:true},landscape:payload.landscape??{variant:'compact',logoAlignment:'left',showCnpj:true,showContact:true},updatedAt:null}};
  return{settings:{orientation:'portrait',opacity:15,size:60,portraitImageKey:workspaceId+'/portrait-existing.png',portraitImageName:'retrato.png',landscapeImageKey:workspaceId+'/landscape-existing.png',landscapeImageName:'paisagem.png',...payload}};
 };
 globalThis.configFunction=async(name,body)=>{calls.push({functionName:name,body});return{user:{id:'invite-a',name:'',email:body.email,status:'pending',accessProfileId:body.accessProfileId,accessProfileName:'Operador',isOwner:false}};};
 const controller=new AbortController();
 assert.deepEqual(await api.fetchCompanies(controller.signal),[{id:'company-a',logoKey:workspaceId+'/companies/existing.png',logoName:'Empresa.png',logoUrl:'https://signed.example.test/'+workspaceId+'/companies/existing.png'}]);
 assert.equal(calls.at(-1).signal,controller.signal);
 const companyInput={cnpj:'',legalName:'Empresa teste',tradeName:'',street:'',number:'',complement:'',district:'',city:'',state:'',zipCode:'',phone:'',email:'',isPrimary:true};
 const companyLogo=new File(['company-logo'],'empresa.png',{type:'image/png'});
 await api.persistCompany(companyInput,'company-a',{file:companyLogo,remove:false,previousKey:workspaceId+'/companies/existing.png'});
 const companyUpload=uploads.at(-1);assert.equal(companyUpload.bucket,'billing-company-logos');assert.match(companyUpload.path,new RegExp('^'+workspaceId+'/companies/[0-9a-f-]+\\.png$'));assert.equal(companyUpload.options.upsert,false);
 assert.equal(calls.at(-1).payload.logoKey,companyUpload.path);assert.equal(calls.at(-1).payload.logoName,'empresa.png');assert.deepEqual(removals.at(-1),{bucket:'billing-company-logos',paths:[workspaceId+'/companies/existing.png']});
 await api.persistSettings({name:'Nome',company:'Empresa',compact:true,email:'forged@example.test'});
 assert.deepEqual(calls.at(-1).payload,{name:'Nome',company:'Empresa',compact:true});
 const members=await api.fetchUsers(controller.signal);assert.equal(members[0].isOwner,true);assert.equal(calls.at(-1).resource,'users');
 await api.inviteUser({email:' MEMBER@EXAMPLE.TEST ',accessProfileId:'profile-a'});assert.equal(calls.at(-1).functionName,'billing-user-invite');assert.equal(calls.at(-1).body.email,'member@example.test');assert.equal(calls.at(-1).body.accessProfileId,'profile-a');assert.match(calls.at(-1).body.requestId,/^[0-9a-f-]{36}$/);
 const disabled=await api.setUserEnabled('membership-a',false);assert.equal(disabled.status,'inactive');assert.equal(calls.at(-1).action,'disable');
 await api.cancelUserInvite('invite-a');assert.equal(calls.at(-1).action,'cancel-invite');
 await api.removeUser('membership-a');assert.equal(calls.at(-1).action,'remove');
 const profiles=await api.fetchAccessProfiles(controller.signal);assert.equal(profiles[0].permissions[0],'companies.read');
 await api.persistAccessProfile({name:'Financeiro',description:'Consulta',permissions:['contracts.read']});assert.equal(calls.at(-1).resource,'access-profiles');assert.equal(calls.at(-1).action,'save');
 const report=await api.fetchReportHeader(controller.signal);assert.equal(report.portrait.variant,'detailed');assert.equal(report.landscape.variant,'compact');
 await api.persistReportHeader({...report,orientation:'landscape'});assert.equal(calls.at(-1).resource,'report-headers');assert.equal(calls.at(-1).payload.orientation,'landscape');
 const reportCompany={id:'company-a',name:'AGRISUL',legalName:'AGRISUL Agrícola Ltda.',cnpj:'04773159000523',street:'Fazenda Santa Ana',number:'s/n',complement:'Zona Rural',district:'',city:'Japoatã',state:'SE',zipCode:'49950000',phone:'1132261428',email:'contato@example.test',logoUrl:null};
 const detailedBrand=api.getReportCompanyDetails(reportCompany,report.portrait);assert.equal(detailedBrand.cnpj,'CNPJ 04.773.159/0005-23');
 assert.equal(detailedBrand.address,'Fazenda Santa Ana, s/n · Zona Rural');assert.equal(detailedBrand.district,'');assert.equal(detailedBrand.city,'Japoatã');assert.equal(detailedBrand.state,'SE');assert.equal(detailedBrand.zipCode,'49950-000');assert.equal(detailedBrand.contact,'(11) 3226-1428 · contato@example.test');
 const compactBrand=api.getReportCompanyDetails(reportCompany,report.landscape);assert.equal(compactBrand.cnpj,detailedBrand.cnpj);assert.equal(compactBrand.address,detailedBrand.address);assert.equal(compactBrand.city,detailedBrand.city);assert.equal(compactBrand.zipCode,detailedBrand.zipCode);assert.equal(compactBrand.contact,detailedBrand.contact);
 const privateBrand=api.getReportCompanyDetails(reportCompany,{...report.portrait,showCnpj:false,showContact:false});assert.deepEqual(privateBrand,{cnpj:'',address:'',district:'',city:'',state:'',zipCode:'',contact:''});
 const existing=await api.fetchWatermark();
 assert.equal(existing.portraitImageUrl,'https://signed.example.test/'+workspaceId+'/portrait-existing.png');
 assert.equal(existing.landscapeImageUrl,'https://signed.example.test/'+workspaceId+'/landscape-existing.png');
 assert.equal(signs.at(-1).seconds,3600);
 const storageFrom=globalThis.configClient.storage.from;
 globalThis.configClient.storage.from=bucket=>({...storageFrom(bucket),createSignedUrls:async paths=>({data:paths.map(path=>({path,signedUrl:null,error:'Object not found'})),error:null})});
 await assert.rejects(api.fetchWatermark(),/Não foi possível carregar as imagens/, 'A missing private file must not silently remove the configured watermark');
 globalThis.configClient.storage.from=storageFrom;
 const portraitFile=new File(['portrait-content'],'novo-retrato.png',{type:'image/png'});
 const landscapeFile=new File(['landscape-content'],'nova-paisagem.jpg',{type:'image/jpeg'});
 const saved=await api.persistWatermark(existing,{portrait:portraitFile,landscape:landscapeFile},{portrait:false,landscape:false});
 const watermarkUploads=uploads.filter(upload=>upload.bucket==='billing-watermarks').slice(-2);
 assert.match(watermarkUploads[0].path,new RegExp('^'+workspaceId+'/portrait/[0-9a-f-]+\\.png$'));
 assert.match(watermarkUploads[1].path,new RegExp('^'+workspaceId+'/landscape/[0-9a-f-]+\\.jpg$'));
 assert.equal(watermarkUploads[0].options.upsert,false);assert.equal(watermarkUploads[1].options.upsert,false);
 assert.equal(calls.at(-1).payload.portraitImageKey,watermarkUploads[0].path);
 assert.equal(calls.at(-1).payload.landscapeImageKey,watermarkUploads[1].path);
 assert.equal(calls.at(-1).payload.imageUrl,undefined);
 assert.equal(saved.portraitImageUrl,'https://signed.example.test/'+watermarkUploads[0].path);
 assert.equal(saved.landscapeImageUrl,'https://signed.example.test/'+watermarkUploads[1].path);
 await api.persistWatermark(saved,{}, {portrait:true,landscape:false});
 assert.equal(calls.at(-1).payload.portraitImageKey,null);
 assert.equal(calls.at(-1).payload.portraitImageName,'');
 assert.equal(calls.at(-1).payload.landscapeImageKey,watermarkUploads[1].path);
 session=null;
 await assert.rejects(api.persistWatermark(existing,{portrait:portraitFile},{}),/Entre na sua conta/);
 await assert.rejects(api.persistCompany(companyInput,undefined,{file:companyLogo,remove:false,previousKey:null}),/Entre na sua conta/);
 assert.equal(uploads.length,3);
 session={user:{id:'owner-a'},access_token:'test-session'};
 globalThis.configRpc=async()=>{throw new Error('Validação do servidor');};
 await assert.rejects(api.persistSettings({name:'',company:'',compact:false,email:''}),/Validação do servidor/);
 console.log('Passed: configuration RPC envelopes, company logo signing/upload/cleanup, auth-derived email, private images, explicit removal, authentication and server errors.');
}finally{await rm(temporary,{recursive:true,force:true});delete globalThis.configRpc;delete globalThis.configFunction;delete globalThis.configClient;}
