import assert from 'node:assert/strict';
import {mkdtemp,readFile,rm,mkdir,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {createRequire} from 'node:module';
import {pathToFileURL} from 'node:url';

const require=createRequire(import.meta.url),{build}=require(require.resolve('esbuild',{paths:[require.resolve('vite')]}));
const directory=await mkdtemp(join(tmpdir(),'contract-summary-details-'));
try{
 const output=join(directory,'summary.mjs');
 await build({stdin:{contents:`export {contractSummaryDetails} from './modules/contratos/utils/contractSummaryDetails'; export {createContractMonthlySummaryPdf} from './modules/contratos/reporting/contractMonthlySummaryPdf';`,resolveDir:process.cwd()},outfile:output,bundle:true,platform:'node',format:'esm'});
 const {contractSummaryDetails,createContractMonthlySummaryPdf}=await import(pathToFileURL(output));
 const metrics={loadedVolume:'250',averageAtr:'121.5',grossAmount:'150000.75',grossPerTon:'600.003',discountAmount:'2000.25',netAmount:'148000.50',netPerTon:'592.002',advanceAmount:'25000.15',receiptAmount:'35000.35',refundedAmount:'0',receivedAmount:'60000.50',pendingAmount:'88000',creditAmount:'0',refundableAmount:'0',billingPending:false};
 const empty={...metrics,loadedVolume:'0',averageAtr:'',grossAmount:'0',discountAmount:'0',netAmount:'0',advanceAmount:'0',receiptAmount:'0',refundedAmount:'0',receivedAmount:'0',pendingAmount:'0',creditAmount:'0',refundableAmount:'0'};
 const advanceMonth={...empty,month:'2026-08',advanceAmount:'987.65',receivedAmount:'987.65',creditAmount:'987.65'};
 const production={month:'2026-09',atrReferenceMonth:'2026-08',loadedVolume:'250',averageLoadAtr:'121.5',atrQuote:'1.253367',billingAmount:'150000.75',billingPending:false,expenseAmount:'',expensesPending:true,resultAmount:''};
 const payment={id:'payment',requestId:'payment-request',kind:'advance',receivedAt:'2026-09-15',referenceMonth:'2026-08',amount:'987.65',document:'RECIBO-987',notes:'Entrada antecipada confirmada.',revision:1};
 const discount={id:'discount',requestId:'discount-request',title:'Acordo de transporte',ratePerTon:'8.001',months:['2026-09','2026-10'],notes:'Condições negociadas.',revision:1,loadedVolume:'250',amount:'2000.25'};
 const contract={id:'12345678-1234-4234-8234-123456789012',title:'Safra',contractNumber:'CTR-TESTE-2026',companyId:'company',companyName:'Empresa de teste',companyCnpj:'',clientId:'client',clientName:'Cliente do resumo completo',clientCnpj:'11222333000181',typeId:'type',typeName:'Fornecimento',stages:[],status:'Ativo',startDate:'2026-08-01',endDate:'2026-12-31',contractedVolume:'1000',loadedVolume:'250',remainingVolume:'750',averageAtr:'121.5',billingAmount:'150000.75',billingPending:false,atrPriceType:'gross',atrPeriodType:'accumulated',value:'',notes:'Orientações comerciais do contrato.',createdAt:'',updatedAt:'',monthlySummary:{criteria:{atrPriceType:'gross',atrPeriodType:'accumulated'},months:[production],totals:{contractedVolume:'1000',loadedVolume:'250',remainingVolume:'750',averageLoadAtr:'121.5',billingAmount:'150000.75',billingPending:false,pendingQuoteMonths:0,expenseAmount:'',expensesPending:true,resultAmount:''}},financialSummary:{months:[advanceMonth,{...metrics,month:'2026-09'},{...empty,month:'2026-10'}],totals:metrics,emptyMonth:empty,payments:[payment],refunds:[],discounts:[discount]}};
 const snapshot=JSON.stringify(contract),model=contractSummaryDetails(contract);
 assert.equal(JSON.stringify(contract),snapshot,'Presentation must not mutate RPC data');
 assert.equal(model.totals.finance,metrics,'Use RPC totals, not a sum of monthly balances');
 assert.deepEqual(model.months.map(item=>item.month),['2026-08','2026-09','2026-10']);
 assert.deepEqual(model.financialItems.map(item=>item.key),['gross','discount','net','advance','receipt','refund','received','pending','credit']);
 for(const [key,value] of [['advance','25.000,15'],['receipt','35.000,35'],['received','60.000,50'],['pending','88.000,00']])assert.ok(model.financialItems.find(item=>item.key===key).value.includes(value));
 assert.ok(model.operationalItems.find(item=>item.label==='Falta entregar').value.includes('750,00'));
 assert.equal(model.salePerTon.gross,'R$ 600,00/t');
 assert.equal(model.salePerTon.net,'R$ 592,00/t');
 const heroSource=await readFile('modules/contratos/components/details/ContractSummaryHero.tsx','utf8');
 const pdfSource=await readFile('modules/contratos/reporting/contractSummaryPdfDocument.ts','utf8');
 const detailSource=await readFile('modules/contratos/components/ContractDetail.tsx','utf8');
 const summaryFinancialSource=await readFile('modules/contratos/components/details/ContractSummaryFinancialOverview.tsx','utf8');
 const reportDialogSource=await readFile('modules/contratos/components/ContractMonthlyReportDialog.tsx','utf8');
 const monthlyChartsSource=await readFile('modules/contratos/components/details/ContractMonthlyCharts.tsx','utf8');
 const heroOrder=['Quantidade do contrato','Quantidade entregue','summary.operationalItems[3].label','Falta entregar'].map(value=>heroSource.indexOf(value));
 assert.ok(heroOrder.every((position,index)=>position>=0&&(index===0||position>heroOrder[index-1])),'Hero KPI rows must keep contract/received, delivered/pending, ATR/sale-per-ton, remaining/credit order');
 assert.match(heroSource,/balances=\[money\[0\],money\[1\],null,money\[2\]\]/);
 assert.doesNotMatch(heroSource,/Quantidade entregue[^\n]+ATR médio/);
 assert.match(heroSource,/label:'Falta entregar'/,'The eighth hero KPI must keep the remaining contract volume');
 assert.match(pdfSource,/row\.averageAtr/,'The PDF daily line must use the server-calculated ATR for each day');
 assert.match(pdfSource,/setLineDashPattern\(\[1\.2,1\],0\)/,'The PDF daily ATR line must be dotted');
 assert.match(pdfSource,/contractDailyLoadsChartRows\(dailyLoads,granularity\)/,'The PDF must aggregate the chart with the selected screen granularity');
 assert.match(pdfSource,/`ATR \$\{formatAtr\(row\.averageAtrText\)\}`[\s\S]+row\.label/,'The PDF must place the bucket ATR between its bar and period label');
 assert.doesNotMatch(pdfSource,/labelTop|point\.label/,'The PDF must not duplicate ATR values in point callouts');
 assert.ok((pdfSource.match(/setLineDashPattern\(\[1\.2,1\],0\)/g)?.length??0)>=2,'Both PDF ATR lines must use the same dotted treatment');
 assert.match(pdfSource,/contractLoadFinancialChartRows\(dailyLoads,granularity\)/,'The PDF financial chart must reuse the selected upper period and granularity');
 assert.match(pdfSource,/Faturado bruto \(barra total\)/,'The PDF legend must explain that gross is the complete bar');
 assert.match(pdfSource,/Líquido \(dentro\)/,'The PDF legend must explain that net is drawn inside gross');
 assert.doesNotMatch(pdfSource,/value>=1000[^\n]+['"]k['"]|['"] mil['"]|['"] mi['"]/,'The PDF financial chart must not abbreviate currency values');
 assert.doesNotMatch(pdfSource,/variationPercent|Variação percentual/,'The PDF must not reuse the obsolete percentage series');
 assert.match(detailSource,/dailyPeriod=\{dailyPeriod\}/,'The summary PDF must receive the daily period currently selected on screen');
 assert.match(detailSource,/onDailyPeriod=\{changeDailyPeriod\}/,'The daily date filter must synchronize the monthly summary');
 assert.match(detailSource,/const monthlyPeriod=contractMonthlyPeriodFromDateRange\(dailyPeriod\)/,'The monthly tables must derive their month range from the single upper filter');
 assert.doesNotMatch(detailSource,/useState<ContractMonthlyPeriod>/,'There must not be a second period state for the lower summary');
 assert.match(summaryFinancialSource,/<ContractMonthlyCharts data=\{dailyLoads\.data\} period=\{dailyPeriod\}/,'The lower financial chart must consume the same filtered loads and granularity as the upper chart');
 assert.match(monthlyChartsSource,/stroke="#d97706"[^>]+strokeOpacity=\{\.52\}[^>]+strokeDasharray="6 5"/,'The monthly ATR series must use the same translucent dotted orange treatment as the load chart');
 assert.match(monthlyChartsSource,/\|ATR \$\{formatAtr\([^}]+\)\} kg\/t/,'Each monthly x-axis label must show its ATR between the chart and month');
 assert.match(reportDialogSource,/\{search:'',from:dailyPeriod\.from,to:dailyPeriod\.to,groupBy:'day'\}/,'The PDF query must use the visible dates without sending presentation granularity to the RPC');
 assert.match(reportDialogSource,/dailyLoads\.data,dailyPeriod/,'The PDF must receive the granularity currently selected on screen');
 assert.ok(model.tables[1].rows[0][1].includes('987,65'));
 assert.equal(model.tables[2].rows[0][0],'15/09/2026');assert.equal(model.tables[2].rows[0][1],'Ago/2026');
 const agreement=model.tables.find(table=>table.title==='Acordos de desconto');
 assert.ok(agreement.rows[0][0].includes('Condições negociadas.'));
 assert.ok(agreement.rows[0][1].includes('8,001/t'),'Preserve the agreed rate precision');
 assert.equal(agreement.rows[0][2],'Set/2026, Out/2026');
 assert.ok(agreement.rows[0][3].includes('250,00'));
 assert.ok(agreement.rows[0][4].includes('2.000,25'),'Use the discount amount returned by the RPC');
 const pending={...metrics,billingPending:true,grossAmount:'',netAmount:'',pendingAmount:'',creditAmount:''};
 const pendingModel=contractSummaryDetails({...contract,financialSummary:{...contract.financialSummary,totals:pending}});
 for(const key of ['gross','net','pending','credit'])assert.equal(pendingModel.financialItems.find(item=>item.key===key).value,'Pendente');
 assert.ok(pendingModel.financialItems.find(item=>item.key==='received').value.includes('60.000,50'));
 const noFinance=contractSummaryDetails({...contract,financialSummary:undefined});
 assert.equal(noFinance.financialItems.find(item=>item.key==='received').value,'—');
 assert.deepEqual(noFinance.salePerTon,{label:'Valor de venda por tonelada',gross:'—',net:'—'});
 const brand={orientation:'portrait',header:{variant:'detailed',logoAlignment:'left',showCnpj:true,showContact:true},company:null,watermark:{imageUrl:null,opacity:15,size:60},issuer:{id:'user',name:'Responsável',email:'responsavel@example.test'},issuedAt:new Date('2026-09-15T12:00:00Z')};
 const pricedLoad=(id,loadedAt,volume,atr,grossAmount,discountAmount,netAmount)=>({id,contractId:contract.id,loadedAt,farmId:'farm',plotId:'plot',farmName:'Fazenda teste',plotName:'Talhão teste',volume,atr,atrReferenceMonth:'2026-09',atrQuote:'1.2',grossAmount,discountAmount,netAmount,billingPending:false,document:'',notes:'',createdAt:'',updatedAt:''});
 const firstLoad=pricedLoad('load-1','2026-09-15','100','120','60000.30','800.10','59200.20'),secondLoad=pricedLoad('load-2','2026-09-16','150','122.5','90000.45','1200.15','88800.30');
 const dailyLoads={filters:{search:'',from:'2026-09-01',to:'2026-09-30',groupBy:'day'},summary:{loadCount:2,volume:'250',farmCount:1,plotCount:1,activeDayCount:2,monthCount:1,averageDailyVolume:'125',averageAtr:'121.5',firstLoadedAt:'2026-09-15',lastLoadedAt:'2026-09-16',grossAmount:'150000.75',discountAmount:'2000.25',netAmount:'148000.50',billingPending:false},monthlyVolumes:[{month:'2026-09',volume:'250',loadCount:2}],groups:[{key:'2026-09-15',label:'2026-09-15',loadCount:1,volume:'100',averageAtr:'120',loads:[firstLoad]},{key:'2026-09-16',label:'2026-09-16',loadCount:1,volume:'150',averageAtr:'122.5',loads:[secondLoad]}]};
 const dailyDayPeriod={from:'2026-09-01',to:'2026-09-30',granularity:'day'};
 const longContract={...contract,notes:('Orientação comercial detalhada. '.repeat(120)+'FIM-DAS-OBSERVACOES'),financialSummary:{...contract.financialSummary,payments:Array.from({length:45},(_,index)=>({...payment,id:'payment-'+index,document:'RECIBO-'+String(index).padStart(3,'0'),notes:index===4?'Detalhes do comprovante. '.repeat(40)+'FIM-DO-COMPROVANTE':'Entrada confirmada.'})),discounts:[{...discount,notes:'Condições do acordo. '.repeat(45)+'FIM-DO-ACORDO'}]}};
 for(const orientation of ['portrait','landscape']){
  const {doc}=await createContractMonthlySummaryPdf(longContract,{...brand,orientation},undefined,dailyLoads,dailyDayPeriod);
  const commands=doc.internal.pages.flat().join('\n');
  for(const text of ['Avanço do carregamento','Quantidade carregada por dia','ATR médio diário','120,00','122,50','Média diária 125,00 t','15/09','16/09','Valor de venda por tonelada','Bruto','600,00/t','Líquido:','592,00/t','Da entrega ao recebimento','Entregas, faturamento e entradas','Faturamento bruto, líquido e ATR por dia','Faturado bruto','Líquido','R$ 60.000,30','R$ 59.200,20','ATR médio','Quantidade entregue','Acordos de desconto','Valor por tonelada','Meses de aplicação','Base entregue','Desconto total','Adiantamentos','Recebimentos','Estornos','Total recebido','Crédito do contrato','Falta entregar','25.000,15','35.000,35','60.000,50','88.000,00','8,001/t','Ago/2026','Out/2026','RECIBO-044','FIM-DO-COMPROVANTE','FIM-DO-ACORDO','FIM-DAS-OBSERVACOES'])assert.ok(commands.includes(text),orientation+' lost '+text);
  assert.ok(!commands.includes('Variação percentual'),orientation+' kept the obsolete percentage legend');
  assert.doesNotMatch(commands,/A ajustar|Dados essenciais|Condições do contrato/);
  assert.ok(doc.getNumberOfPages()>2);
  for(const page of doc.internal.pages.slice(1))for(const command of page){
   if(!command.includes(' Tj')||/Emitido por|Página/.test(command))continue;
   const position=command.match(/[-\d.]+ ([-\d.]+) Td/),leading=command.match(/([-\d.]+) TL/);
   if(position){const lastY=Number(position[1])-(command.match(/T\*/g)?.length??0)*Number(leading?.[1]??0);assert.ok(lastY>23*72/25.4,'Body text must stay above the footer in '+orientation);}
  }
  if(process.env.BILLING_SUMMARY_ARTIFACTS){const folder=resolve(process.env.BILLING_SUMMARY_ARTIFACTS);await mkdir(folder,{recursive:true});await writeFile(join(folder,'resumo-'+orientation+'.pdf'),new Uint8Array(doc.output('arraybuffer')));await writeFile(join(folder,'contract.json'),JSON.stringify(contract));}
 }
 const weeklyPeriod={...dailyDayPeriod,granularity:'week'};
 const intervalContract={...contract,financialSummary:{...contract.financialSummary,payments:[],refunds:[],discounts:[]}};
 const {doc:weeklyDoc}=await createContractMonthlySummaryPdf(intervalContract,brand,{from:'2026-08',to:'2026-10'},dailyLoads,weeklyPeriod),weeklyCommands=weeklyDoc.internal.pages.flat().join('\n');
 for(const text of ['Quantidade carregada por semana','ATR médio semanal','ATR 121,50','Média semanal 250,00 t','Faturamento bruto, líquido e ATR por semana','R$ 150.000,75','R$ 148.000,50','Período: 01/09/2026 a 30/09/2026'])assert.ok(weeklyCommands.includes(text),'Weekly PDF lost '+text);
 assert.ok(!weeklyCommands.includes('Out/2026'),'The shared daily interval must exclude October from the PDF monthly summary');
 const nineDayLoads={...dailyLoads,summary:{...dailyLoads.summary,loadCount:9,volume:'450',activeDayCount:9,averageDailyVolume:'50',averageAtr:'114'},groups:Array.from({length:9},(_,index)=>({key:`2026-09-${String(index+1).padStart(2,'0')}`,label:`2026-09-${String(index+1).padStart(2,'0')}`,loadCount:1,volume:'50',averageAtr:String(110+index),loads:[]}))};
 const {doc:pagedDoc}=await createContractMonthlySummaryPdf(contract,brand,undefined,nineDayLoads,dailyDayPeriod),pagedCommands=pagedDoc.internal.pages.flat().join('\n');
 assert.equal(pagedCommands.match(/Quantidade carregada por dia/g)?.length,2,'Nine daily bars must produce two finite PDF chart panels');
 assert.equal(pagedCommands.match(/08\/09/g)?.length,2,'The safe pagination overlap must repeat only the boundary bar');
 assert.equal(pagedCommands.match(/09\/09/g)?.length,1,'The final daily bar must render once');
 console.log('Passed: nine financial indicators, delivery balance, payment-only months, credits, unavailable/pending states, RPC totals, full histories, long notes and PDF footer safety in both orientations.');
}finally{await rm(directory,{recursive:true,force:true});}
