import assert from 'node:assert/strict';
import {readFileSync,readdirSync,mkdirSync} from 'node:fs';
import {createRequire} from 'node:module';
import {DatabaseSync} from 'node:sqlite';
const require=createRequire(import.meta.url);const {build}=require(require.resolve('esbuild',{paths:[require.resolve('vite')]}));
mkdirSync('.sites-runtime/tests',{recursive:true});
const plugins=[{name:'fixtures',setup(b){b.onResolve({filter:/^(cloudflare:workers|next\/headers|next\/navigation)$/},a=>({path:a.path,namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},a=>({contents:a.path==='cloudflare:workers'?'export const env=globalThis.farmsTestEnv;':a.path==='next/headers'?'export async function headers(){return globalThis.farmsHeaders;}':'export function redirect(){throw new Error("Unexpected redirect")}'}));}}];
await build({entryPoints:['app/api/farms/route.ts'],outfile:'.sites-runtime/tests/farms.mjs',bundle:true,platform:'node',format:'esm',plugins});
await build({entryPoints:['modules/cadastro/fazenda/utils/farmFormat.ts'],outfile:'.sites-runtime/tests/farm-format.mjs',bundle:true,platform:'node',format:'esm'});
const sqlite=new DatabaseSync(':memory:');for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sqlite.exec(readFileSync('drizzle/'+f,'utf8'));
let failWrite=false;
const DB={prepare(sql){return{bind(...args){return{async first(){return sqlite.prepare(sql).get(...args)||null;},async all(){return{results:sqlite.prepare(sql).all(...args)};},async run(){if(failWrite)throw new Error('storage failure');const result=sqlite.prepare(sql).run(...args);return {meta:{changes:result.changes}};}};}};}};
globalThis.farmsTestEnv={DB};globalThis.farmsHeaders=new Headers();
const api=await import('../.sites-runtime/tests/farms.mjs');const {formatHectares}=await import('../.sites-runtime/tests/farm-format.mjs');
const signIn=user=>{globalThis.farmsHeaders=new Headers(user?{'oai-authenticated-user-id':user,'oai-authenticated-user-email':user+'@example.test'}:{});};
const base={name:'Fazenda Boa Vista',areaHa:'125,500001',city:'Japoatã',state:'se'};
const request=(method,data,origin='https://farms.test')=>new Request('https://farms.test/api/farms',{method,headers:{'Content-Type':'application/json',origin},body:JSON.stringify(data)});
assert.equal((await api.GET()).status,401);assert.equal((await api.POST(request('POST',base))).status,401);
signIn('owner-a');let response=await api.POST(request('POST',base));assert.equal(response.status,201);const a=(await response.json()).farm;assert.equal(a.areaHa,'125.500001');assert.equal(a.state,'SE');assert.equal(formatHectares('1125.500001'),'1.125,500001');
let rows=(await (await api.GET()).json()).farms;assert.equal(rows.length,1);assert.equal(rows[0].city,base.city);assert.equal(rows[0].name,base.name);assert.equal(rows[0].areaHa,'125.500001');
signIn('owner-b');assert.equal((await (await api.GET()).json()).farms.length,0);assert.equal((await api.PATCH(request('PATCH',{...base,id:a.id}))).status,404);assert.equal((await api.POST(request('POST',base))).status,201);
signIn('owner-a');response=await api.PATCH(request('PATCH',{...base,id:a.id,name:'Fazenda Atualizada',areaHa:'180.75',city:'Aracaju'}));assert.equal(response.status,200);rows=(await (await api.GET()).json()).farms;assert.equal(rows[0].name,'Fazenda Atualizada');assert.equal(rows[0].areaHa,'180.75');assert.equal(rows[0].city,'Aracaju');
for(const data of [{...base,name:''},{...base,city:''},{...base,state:'XX'},{...base,areaHa:'0'},{...base,areaHa:'-1'},{...base,areaHa:'1.000,50'},{...base,areaHa:'1e9'},{...base,areaHa:'1,1234567'}])assert.equal((await api.POST(request('POST',data))).status,400);
assert.equal((await api.POST(request('POST',base,'https://other.test'))).status,403);
failWrite=true;assert.equal((await api.PATCH(request('PATCH',{...base,id:a.id}))).status,503);rows=(await (await api.GET()).json()).farms;assert.equal(rows[0].areaHa,'180.75');
sqlite.close();console.log('Passed: farm create/read/edit persistence, exact hectares and formatting, owner isolation, required fields, valid UF, positive area and recoverable save failure.');
