import assert from 'node:assert/strict';
import {readFileSync,readdirSync,mkdirSync} from 'node:fs';
import {createRequire} from 'node:module';
import {DatabaseSync} from 'node:sqlite';
const require=createRequire(import.meta.url);const {build}=require(require.resolve('esbuild',{paths:[require.resolve('vite')]}));
mkdirSync('.sites-runtime/tests',{recursive:true});
const plugins=[{name:'fixtures',setup(b){b.onResolve({filter:/^(cloudflare:workers|next\/headers|next\/navigation)$/},a=>({path:a.path,namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},a=>({contents:a.path==='cloudflare:workers'?'export const env=globalThis.plotTestEnv;':a.path==='next/headers'?'export async function headers(){return globalThis.plotHeaders;}':'export function redirect(){throw new Error("Unexpected redirect")}'}));}}];
for(const [entry,out] of [['app/api/plots/route.ts','plots'],['app/api/farms/route.ts','plot-farms']])await build({entryPoints:[entry],outfile:'.sites-runtime/tests/'+out+'.mjs',bundle:true,platform:'node',format:'esm',plugins});
const sqlite=new DatabaseSync(':memory:');sqlite.exec('PRAGMA foreign_keys=ON');for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sqlite.exec(readFileSync('drizzle/'+f,'utf8'));
const DB={prepare(sql){return{bind(...args){return{async first(){return sqlite.prepare(sql).get(...args)||null;},async all(){return{results:sqlite.prepare(sql).all(...args)};},async run(){const result=sqlite.prepare(sql).run(...args);return {meta:{changes:result.changes}};}};}};}};
globalThis.plotTestEnv={DB};globalThis.plotHeaders=new Headers();
const api=await import('../.sites-runtime/tests/plots.mjs');const farms=await import('../.sites-runtime/tests/plot-farms.mjs');
const signIn=user=>{globalThis.plotHeaders=new Headers(user?{'oai-authenticated-user-id':user,'oai-authenticated-user-email':user+'@example.test'}:{});};
const request=(method,data,origin='https://plots.test')=>new Request('https://plots.test/api/plots',{method,headers:{'Content-Type':'application/json',origin},body:JSON.stringify(data)});
const get=farmId=>new Request('https://plots.test/api/plots?farmId='+farmId);
const farmInput={name:'Fazenda Teste',areaHa:'10',city:'Japoatã',state:'SE'};
assert.equal((await api.GET(get('missing'))).status,401);assert.equal((await api.POST(request('POST',{name:'Talhão 1',areaHa:'4',farmId:'x'}))).status,401);
signIn('owner-a');let response=await farms.POST(request('POST',farmInput));assert.equal(response.status,201);const farm=(await response.json()).farm;
const create=(name,areaHa,farmId=farm.id)=>api.POST(request('POST',{name,areaHa,farmId}));
const load=async(farmId=farm.id)=>(await (await api.GET(get(farmId))).json()).data;
let data=await load();assert.equal(data.plots.length,0);assert.equal(data.availableUnits,10000000);
response=await create('Talhão 1','4');assert.equal(response.status,201);const first=(await response.json()).data.plots[0];
response=await create('Talhão 2','3,33');assert.equal(response.status,201);data=await load();assert.equal(data.usedUnits,7330000);assert.equal(data.availableUnits,2670000);assert.equal(data.plots[1].areaHa,'3.33');
assert.equal((await create('Talhão excesso','2.670001')).status,409);assert.equal((await load()).plots.length,2);
assert.equal((await create('Talhão 3','2,67')).status,201);assert.equal((await load()).availableUnits,0);assert.equal((await create('Sem espaço','0.000001')).status,409);
assert.equal((await api.PATCH(request('PATCH',{id:first.id,farmId:farm.id,name:'Talhão 1 editado',areaHa:'3.5'}))).status,200);assert.equal((await load()).availableUnits,500000);
assert.equal((await api.PATCH(request('PATCH',{id:first.id,farmId:farm.id,name:'Talhão 1 editado',areaHa:'4.000001'}))).status,409);assert.equal((await load()).usedUnits,9500000);
assert.equal((await farms.PATCH(request('PATCH',{...farmInput,id:farm.id,areaHa:'9.49'}))).status,409);assert.equal((await load()).totalUnits,10000000);
assert.equal((await farms.PATCH(request('PATCH',{...farmInput,id:farm.id,areaHa:'9.5'}))).status,200);assert.equal((await load()).availableUnits,0);
response=await farms.POST(request('POST',{...farmInput,name:'Fazenda concorrente'}));const concurrentFarm=(await response.json()).farm;
const concurrent=await Promise.all([create('Talhão A','6',concurrentFarm.id),create('Talhão B','6',concurrentFarm.id)]);assert.deepEqual(concurrent.map(r=>r.status).sort(),[201,409]);assert.equal((await load(concurrentFarm.id)).usedUnits,6000000);
assert.equal((await api.PATCH(request('PATCH',{id:first.id,farmId:concurrentFarm.id,name:'Mover indevido',areaHa:'1'}))).status,404);
response=await farms.POST(request('POST',{...farmInput,name:'Fazenda precisão',areaHa:'0.3'}));const tiny=(await response.json()).farm;assert.equal((await create('Talhão A','0.1',tiny.id)).status,201);assert.equal((await create('Talhão B','0.2',tiny.id)).status,201);assert.equal((await load(tiny.id)).availableUnits,0);
response=await farms.POST(request('POST',{...farmInput,name:'Fazenda limite alto',areaHa:'999999999.999999'}));const large=(await response.json()).farm;assert.equal((await create('Área total','999999999.999999',large.id)).status,201);assert.equal((await load(large.id)).availableUnits,0);
signIn('owner-b');assert.equal((await api.GET(get(farm.id))).status,404);assert.equal((await create('Talhão indevido','1')).status,404);assert.equal((await api.PATCH(request('PATCH',{id:first.id,farmId:farm.id,name:'Indevido',areaHa:'1'}))).status,404);
signIn('owner-a');assert.equal((await create('Inválido','0')).status,400);assert.equal((await create('Inválido','-1')).status,400);assert.equal((await create('Inválido','1e4')).status,400);assert.equal((await api.POST(request('POST',{name:'Teste',areaHa:'1',farmId:farm.id},'https://other.test'))).status,403);
sqlite.close();console.log('Passed: farm-linked plots, 4 + 3.33 hectares, exact capacity and decimals, edit capacity, farm shrink protection, concurrent writes, cross-farm and owner isolation.');
