import assert from 'node:assert/strict';
import {readFileSync,readdirSync,mkdirSync} from 'node:fs';
import {createRequire} from 'node:module';
import {DatabaseSync} from 'node:sqlite';
const require=createRequire(import.meta.url);const {build}=require(require.resolve('esbuild',{paths:[require.resolve('vite')]}));mkdirSync('.sites-runtime/tests',{recursive:true});
await build({entryPoints:['app/api/cultural-practices/route.ts'],outfile:'.sites-runtime/tests/practices.mjs',bundle:true,platform:'node',format:'esm',plugins:[{name:'fixtures',setup(b){b.onResolve({filter:/^(cloudflare:workers|next\/headers|next\/navigation)$/},a=>({path:a.path,namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},a=>({contents:a.path==='cloudflare:workers'?'export const env=globalThis.practiceEnv;':a.path==='next/headers'?'export async function headers(){return globalThis.practiceHeaders;}':'export function redirect(){throw new Error("Unexpected redirect")}'}));}}]});
const sqlite=new DatabaseSync(':memory:');for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sqlite.exec(readFileSync('drizzle/'+f,'utf8'));
let failWrite=false;const DB={prepare(sql){return{bind(...args){return{async first(){return sqlite.prepare(sql).get(...args)||null;},async all(){return{results:sqlite.prepare(sql).all(...args)};},async run(){if(failWrite)throw new Error('storage failure');const r=sqlite.prepare(sql).run(...args);return{meta:{changes:r.changes}};}};}};}};
globalThis.practiceEnv={DB};globalThis.practiceHeaders=new Headers();const api=await import('../.sites-runtime/tests/practices.mjs');
const signIn=user=>{globalThis.practiceHeaders=new Headers(user?{'oai-authenticated-user-id':user,'oai-authenticated-user-email':user+'@example.test'}:{});};
const req=(method,data,origin='https://practice.test')=>new Request('https://practice.test/api/cultural-practices',{method,headers:{'Content-Type':'application/json',origin},body:JSON.stringify(data)});
const base={name:'Adubação',description:'Descrição de teste.\nSegunda linha.'};
assert.equal((await api.GET()).status,401);assert.equal((await api.POST(req('POST',base))).status,401);
signIn('owner-a');let response=await api.POST(req('POST',base));assert.equal(response.status,201);const record=(await response.json()).practice;let rows=(await (await api.GET()).json()).practices;assert.equal(rows[0].name,base.name);assert.equal(rows[0].description,base.description);
assert.equal((await api.POST(req('POST',{name:' ADUBACAO ',description:''}))).status,409);
assert.equal((await api.PATCH(req('PATCH',{id:record.id,name:'Trato atualizado',description:'Nova descrição'}))).status,200);rows=(await (await api.GET()).json()).practices;assert.equal(rows[0].description,'Nova descrição');
signIn('owner-b');assert.equal((await (await api.GET()).json()).practices.length,0);assert.equal((await api.PATCH(req('PATCH',{...base,id:record.id}))).status,404);assert.equal((await api.POST(req('POST',base))).status,201);
signIn('owner-a');assert.equal((await api.POST(req('POST',{name:'Outro trato',description:''}))).status,201);assert.equal((await api.POST(req('POST',{name:'',description:''}))).status,400);assert.equal((await api.POST(req('POST',{name:'Teste',description:'x'.repeat(2001)}))).status,400);assert.equal((await api.POST(req('POST',base,'https://other.test'))).status,403);
failWrite=true;assert.equal((await api.PATCH(req('PATCH',{...base,id:record.id}))).status,503);rows=(await (await api.GET()).json()).practices;assert.equal(rows.find(r=>r.id===record.id).description,'Nova descrição');
sqlite.close();console.log('Passed: cultural practice create/read/edit persistence, optional multiline description, normalized duplicates, owner isolation, validation and recoverable failure.');
