import assert from 'node:assert/strict';
import {mkdtemp,readFile,rm} from 'node:fs/promises';
import {join,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {createRequire} from 'node:module';
import {pathToFileURL} from 'node:url';
import {realtimeResources} from '../shared/query/realtimeResources.ts';
const require=createRequire(import.meta.url),{build}=require(require.resolve('esbuild',{paths:[require.resolve('vite')]}));
const directory=await mkdtemp(join(tmpdir(),'summary-dashboard-'));
try{
 const calls=[];globalThis.__summaryRpc=async(...args)=>{calls.push(args);return {range:{from:'2025-09-18',to:'2026-09-17'}};};
 const servicePath=join(directory,'service.mjs');
 await build({entryPoints:['modules/resumo/services/summaryService.ts'],outfile:servicePath,bundle:true,platform:'node',format:'esm',plugins:[{name:'rpc-fixture',setup(builder){builder.onResolve({filter:/shared\/supabase\/rpc$/},()=>({path:'rpc',namespace:'fixture'}));builder.onLoad({filter:/.*/,namespace:'fixture'},()=>({contents:'export const rpcRequest=(...args)=>globalThis.__summaryRpc(...args);',loader:'js'}));}}]});
 const {fetchExecutiveSummary}=await import(pathToFileURL(servicePath).href),controller=new AbortController();
 await fetchExecutiveSummary('company-a','2025-09-18','2026-09-17',controller.signal);
 assert.deepEqual(calls,[['summary','dashboard',{companyId:'company-a',from:'2025-09-18',to:'2026-09-17'},controller.signal]]);
 for(const table of ['billing_contracts','billing_contract_loads','billing_contract_payments','billing_contract_discounts','billing_farms','billing_farm_plots','billing_planning_periods','billing_planning_allocations','billing_planning_harvest_targets','billing_planning_field_logs'])assert.ok(realtimeResources[table].includes('summary'),`${table} must refresh the executive summary`);

 const months=Array.from({length:25},(_,index)=>{const date=new Date(2024,8+index,1),month=`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}`;return {month,loadCount:index+1,loadedVolume:String((index+1)*10),billingPending:index===24,pendingLoadCount:index===24?1:0,grossAmount:index===24?'':String((index+1)*1000),discountAmount:String((index+1)*10),netAmount:index===24?'':String((index+1)*990),advanceAmount:'0',receiptAmount:String(index*100),receivedAmount:String(index*100),pendingAmount:index===24?'':String(index*890),creditAmount:'0'};});
 const contracts=Array.from({length:42},(_,index)=>({id:String(index),clientName:index===41?'Cliente final do painel':'Cliente '+index,contractNumber:'DASH-'+index,title:'Contrato '+index,status:'Ativo',loadCount:index+1,loadedVolume:String(index+1),billingPending:false,grossAmount:'1000',discountAmount:'10',netAmount:'990',receivedAmount:'100',pendingAmount:'890'}));
 const monthlyOperations=months.map((item,index)=>({month:item.month,loadCount:item.loadCount,loadedVolume:item.loadedVolume,averageAtr:index===24?'':'125',averageLoadVolume:'10',contractCount:1,farmCount:1,plotCount:1}));
 const contractPerformance=contracts.map((item,index)=>({id:item.id,clientName:item.clientName,contractNumber:item.contractNumber,title:item.title,status:item.status,contractedVolume:'100',periodLoadCount:item.loadCount,periodLoadedVolume:item.loadedVolume,averageAtr:'125',averageLoadVolume:'10',totalLoadedVolume:String(index+1),remainingVolume:String(99-index),deliveryPercent:String(index+1)}));
 const data={range:{from:'2024-09-01',to:'2026-09-30',dayCount:760,generatedAt:'2026-09-17T12:00:00Z'},totals:{contractCount:42,activeContractCount:42,loadCount:325,loadedVolume:'3250',farmCount:1,plotCount:1,billingPending:true,pendingLoadCount:1,grossAmount:'',discountAmount:'3250',netAmount:'',advanceAmount:'0',receiptAmount:'30000',receivedAmount:'30000',pendingAmount:'',creditAmount:''},comparison:{from:'2022-08-03',to:'2024-08-31',loadCount:1,loadedVolume:'100',netAmount:'900',receivedAmount:'100',volumeChangePercent:'25',netChangePercent:'',receivedChangePercent:'10'},months,contractStatus:[{status:'Ativo',count:42}],contracts,farms:[{id:'farm',name:'Fazenda PDF',areaHa:'50',plotCount:1,loadCount:325,loadedVolume:'3250',billingPending:false,grossAmount:'1000',discountAmount:'10',netAmount:'990'}],agriculture:{scope:'workspace',registeredFarmCount:1,registeredPlotCount:1,farmAreaHa:'50',plotAreaHa:'25'},planning:{scope:'workspace',periodCount:1,activePeriodCount:1,periodName:'Safra PDF',progressAsOf:'2026-09-30',targetAreaHa:'20',allocatedAreaHa:'20',plantedAreaHa:'5',managedAreaHa:'4',lostAreaHa:'0',fieldLogCount:2,managementEventCount:1,harvestTargetTons:'100',harvestedTons:'10',plantingPercent:'25',harvestPercent:'10'},management:[{id:'practice',name:'Adubação de plantio',eventCount:1,areaHa:'4'}],operationalTotals:{loadCount:325,loadedVolume:'3250',averageAtr:'125',averageLoadVolume:'10',contractCount:42,farmCount:1,plotCount:1},monthlyOperations,farmPerformance:[{id:'farm',name:'Fazenda PDF',areaHa:'50',loadCount:325,loadedVolume:'3250',averageAtr:'125',averageLoadVolume:'10',tonsPerHa:'65',plotCount:1,contractCount:42}],plotPerformance:[{id:'plot',name:'Talhão PDF',farmId:'farm',farmName:'Fazenda PDF',areaHa:'25',loadCount:325,loadedVolume:'3250',averageAtr:'125',averageLoadVolume:'10',tonsPerHa:'130',contractCount:42}],contractPerformance,planningPerformance:{periodName:'Safra PDF',farms:[{id:'farm',name:'Fazenda PDF',plotCount:1,targetAreaHa:'20',plantedAreaHa:'5',plantingPercent:'25',targetTons:'100',harvestedTons:'10',remainingTons:'90',harvestPercent:'10',loadCount:1}],plots:[{id:'plot',name:'Talhão PDF',farmId:'farm',farmName:'Fazenda PDF',areaHa:'25',targetAreaHa:'20',plantedAreaHa:'5',plantingPercent:'25',targetTons:'100',harvestedTons:'10',remainingTons:'90',harvestPercent:'10',loadCount:1}]}};
 const snapshot={data,companyId:'company-a'},before=structuredClone(snapshot),pdfPath=join(directory,'pdf.mjs');
 await build({entryPoints:['modules/resumo/reporting/summaryPdf.ts'],outfile:pdfPath,bundle:true,platform:'node',format:'esm'});
 const {createSummaryPdf}=await import(pathToFileURL(pdfPath).href);
 const {doc,fileName}=await createSummaryPdf(snapshot,{company:null,header:{variant:'compact',logoAlignment:'left',showCnpj:true,showContact:true},watermark:{imageUrl:null,opacity:15,size:60},issuer:{id:'user',name:'Teste',email:''},issuedAt:new Date('2026-09-17T12:00:00Z')});
 assert.equal(fileName,'resumo-gerencial-2024-09-01-a-2026-09-30.pdf');assert.ok(doc.getNumberOfPages()>=7,'Long series and tables must paginate');
 const commands=doc.internal.pages.slice(1).flat().join('\n');assert.ok(commands.includes('DASH-41'),'Final contract must reach the PDF');assert.ok(commands.includes('Cliente final do painel'));assert.ok(commands.includes('Safra PDF'));assert.ok(commands.includes('Talhão PDF'));assert.ok(commands.includes('Meses com carregamentos'));assert.deepEqual(snapshot,before,'PDF generation must not mutate its snapshot');
 const source=await readFile('modules/resumo/components/ResumoPage.tsx','utf8'),operationsSource=await readFile('modules/resumo/components/SummaryOperational.tsx','utf8');assert.match(source,/defaultRange/);assert.match(source,/Exportar PDF completo/);assert.match(source,/365 dias por padrão/);assert.match(operationsSource,/filter\(row=>row\.loadCount>0\|\|Number\(row\.loadedVolume\)>0\)/);
 console.log('PASS: executive summary RPC client, Realtime dependencies, 365-day UI and complete multipage immutable PDF.');
}finally{
 delete globalThis.__summaryRpc;
 if(!resolve(directory).startsWith(join(resolve(tmpdir()),'summary-dashboard-')))throw Error('Unsafe test cleanup path');
 await rm(directory,{recursive:true,force:true});
}
