import assert from 'node:assert/strict';
import {readFileSync,readdirSync,mkdirSync} from 'node:fs';
import {createRequire} from 'node:module';
import {DatabaseSync} from 'node:sqlite';
const require=createRequire(import.meta.url);const {build}=require(require.resolve('esbuild',{paths:[require.resolve('vite')]}));mkdirSync('.sites-runtime/tests',{recursive:true});
const plugins=[{name:'fixtures',setup(b){b.onResolve({filter:/^(cloudflare:workers|next\/headers|next\/navigation)$/},a=>({path:a.path,namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},a=>({contents:a.path==='cloudflare:workers'?'export const env=globalThis.catalogEnv;':a.path==='next/headers'?'export async function headers(){return globalThis.catalogHeaders;}':'export function redirect(){throw new Error("Unexpected redirect")}'}));}}];
for(const name of ['contract-types','cultures'])await build({entryPoints:['app/api/'+name+'/route.ts'],outfile:'.sites-runtime/tests/'+name+'.mjs',bundle:true,platform:'node',format:'esm',plugins});
const sqlite=new DatabaseSync(':memory:');sqlite.exec('PRAGMA foreign_keys=ON');for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sqlite.exec(readFileSync('drizzle/'+f,'utf8'));
const DB={prepare(sql){return{bind(...args){return{async first(){return sqlite.prepare(sql).get(...args)||null;},async all(){return{results:sqlite.prepare(sql).all(...args)};},async run(){const result=sqlite.prepare(sql).run(...args);return {meta:{changes:result.changes}};}};}};}};globalThis.catalogEnv={DB};globalThis.catalogHeaders=new Headers();
const types=await import('../.sites-runtime/tests/contract-types.mjs');const cultures=await import('../.sites-runtime/tests/cultures.mjs');
const signIn=user=>{globalThis.catalogHeaders=new Headers(user?{'oai-authenticated-user-id':user,'oai-authenticated-user-email':user+'@example.test'}:{});};
const req=(method,data,origin='https://catalog.test')=>new Request('https://catalog.test/api/catalog',{method,headers:{'Content-Type':'application/json',origin},body:JSON.stringify(data)});
const getType=id=>new Request('https://catalog.test/api/contract-types'+(id?'?id='+id:''));
const stages=[{id:'step-a',name:'Etapa A'},{id:'step-b',name:'Etapa B'}];
assert.equal((await types.GET(getType())).status,401);assert.equal((await cultures.GET()).status,401);assert.equal((await types.POST(req('POST',{name:'Manual',stages}))).status,401);assert.equal((await cultures.POST(req('POST',{kind:'culture',name:'Cana'}))).status,401);
signIn('owner-a');let response=await types.POST(req('POST',{name:'Contrato manual',stages}));assert.equal(response.status,201);const manual=(await response.json()).type;
response=await types.POST(req('POST',{name:'Contrato semimecanizado',stages:[{id:'semi-a',name:'Etapa exclusiva'}]}));assert.equal(response.status,201);const semi=(await response.json()).type;
assert.equal((await types.PATCH(req('PATCH',{id:manual.id,name:manual.name,stages:[stages[1],stages[0]]}))).status,200);assert.deepEqual((await (await types.GET(getType(manual.id))).json()).type.stages.map(s=>s.id),['step-b','step-a']);assert.equal((await (await types.GET(getType(semi.id))).json()).type.stages[0].name,'Etapa exclusiva');
assert.equal((await types.POST(req('POST',{name:'  CONTRATO   MANUAL  ',stages:[]}))).status,409);assert.equal((await types.POST(req('POST',{name:'Inválido',stages:[stages[0],stages[0]]}))).status,400);assert.equal((await types.POST(req('POST',{name:'Inválido',stages:[{id:'a',name:''}]}))).status,400);
response=await cultures.POST(req('POST',{kind:'culture',name:'Cana'}));assert.equal(response.status,201);const cana=(await response.json()).id;
response=await cultures.POST(req('POST',{kind:'subtype',cultureId:cana,name:'Cana soca'}));assert.equal(response.status,201);const soca=(await response.json()).id;
assert.equal((await cultures.POST(req('POST',{kind:'subtype',cultureId:cana,name:'Cana planta'}))).status,201);
let rows=(await (await cultures.GET()).json()).cultures;assert.equal(rows[0].name,'Cana');assert.deepEqual(rows[0].subtypes.map(s=>s.name),['Cana planta','Cana soca']);
assert.equal((await cultures.POST(req('POST',{kind:'culture',name:'  CANA '}))).status,409);assert.equal((await cultures.POST(req('POST',{kind:'subtype',cultureId:cana,name:'CANA SOCA'}))).status,409);
response=await cultures.POST(req('POST',{kind:'culture',name:'Outra cultura'}));const other=(await response.json()).id;assert.equal((await cultures.PATCH(req('PATCH',{kind:'subtype',id:soca,cultureId:other,name:'Movimento indevido'}))).status,404);
assert.equal((await cultures.PATCH(req('PATCH',{kind:'culture',id:cana,name:'Cana-de-açúcar'}))).status,200);rows=(await (await cultures.GET()).json()).cultures;assert.equal(rows.find(c=>c.id===cana).subtypes.length,2);
signIn('owner-b');assert.equal((await (await cultures.GET()).json()).cultures.length,0);assert.equal((await (await types.GET(getType())).json()).types.length,0);assert.equal((await types.PATCH(req('PATCH',{id:manual.id,name:'Indevido',stages:[]}))).status,404);assert.equal((await cultures.POST(req('POST',{kind:'subtype',cultureId:cana,name:'Indevido'}))).status,404);assert.equal((await cultures.PATCH(req('PATCH',{kind:'culture',id:cana,name:'Indevido'}))).status,404);assert.equal((await types.POST(req('POST',{name:manual.name,stages:[]}))).status,201);
signIn('owner-a');assert.equal((await types.POST(req('POST',{name:'Bloqueio',stages:[]},'https://other.test'))).status,403);assert.equal((await cultures.POST(req('POST',{kind:'culture',name:'Bloqueio'},'https://other.test'))).status,403);
sqlite.close();console.log('Passed: independent contract stages/order, stable stage ids, culture/subtype persistence and hierarchy, edits, duplicate names, validation and ownership isolation.');
