import assert from 'node:assert/strict';
import {readFileSync,readdirSync,mkdirSync} from 'node:fs';
import {createRequire} from 'node:module';
import {DatabaseSync} from 'node:sqlite';
const require=createRequire(import.meta.url);
const {build}=require(require.resolve('esbuild',{paths:[require.resolve('vite')]}));
mkdirSync('.sites-runtime/tests',{recursive:true});
const plugins=[{name:'fixtures',setup(b){b.onResolve({filter:/^(cloudflare:workers|next\/headers|next\/navigation)$/},a=>({path:a.path,namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},a=>({contents:a.path==='cloudflare:workers'?'export const env=globalThis.watermarkTestEnv;':a.path==='next/headers'?'export async function headers(){return globalThis.watermarkHeaders;}':'export function redirect(){throw new Error("Unexpected redirect")}'}));}}];
await build({entryPoints:['app/api/watermark/route.ts'],outfile:'.sites-runtime/tests/watermark.mjs',bundle:true,platform:'node',format:'esm',plugins});
await build({entryPoints:['app/api/watermark/image/route.ts'],outfile:'.sites-runtime/tests/watermark-image.mjs',bundle:true,platform:'node',format:'esm',plugins});
const sqlite=new DatabaseSync(':memory:');for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sqlite.exec(readFileSync('drizzle/'+f,'utf8'));
let failWrite=false;const objects=new Map();
const DB={prepare(sql){return {bind(...args){return {async first(){return sqlite.prepare(sql).get(...args)||null;},async run(){if(failWrite)throw new Error('storage failure');return sqlite.prepare(sql).run(...args);}}}}}};
const BUCKET={async put(key,bytes,options){objects.set(key,{body:bytes,httpMetadata:options.httpMetadata});},async get(key){return objects.get(key)||null;},async delete(key){objects.delete(key);}};
globalThis.watermarkTestEnv={DB,BUCKET};globalThis.watermarkHeaders=new Headers();
const api=await import('../.sites-runtime/tests/watermark.mjs');const imageApi=await import('../.sites-runtime/tests/watermark-image.mjs');
const signIn=user=>{globalThis.watermarkHeaders=new Headers(user?{'oai-authenticated-user-id':user,'oai-authenticated-user-email':user+'@example.test'}:{});};
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl6lN0AAAAASUVORK5CYII=','base64');
const request=(data={},file,origin='https://watermark.test')=>{const body=new FormData();for(const [k,v] of Object.entries({orientation:'portrait',opacity:15,size:60,...data}))body.set(k,String(v));if(file)body.set('image',file);return new Request('https://watermark.test/api/watermark',{method:'POST',headers:{origin},body});};
assert.equal((await api.GET()).status,401);assert.equal((await imageApi.GET()).status,401);assert.equal((await api.POST(request())).status,401);
signIn('owner-a');let response=await api.GET();assert.equal(response.status,200);assert.equal((await response.json()).settings.imageUrl,null);
response=await api.POST(request({orientation:'landscape',opacity:27,size:80},new File([png],'logo.png',{type:'image/png'})));assert.equal(response.status,200);let saved=(await response.json()).settings;assert.equal(saved.orientation,'landscape');assert.equal(saved.opacity,27);assert.equal(saved.size,80);assert.equal(saved.imageName,'logo.png');assert.ok(saved.imageUrl.startsWith('/api/watermark/image?'));assert.equal(objects.size,1);
response=await imageApi.GET();assert.equal(response.status,200);assert.equal(response.headers.get('content-type'),'image/png');assert.deepEqual(Buffer.from(await response.arrayBuffer()),png);
signIn('owner-b');assert.equal((await imageApi.GET()).status,404);assert.equal((await (await api.GET()).json()).settings.imageUrl,null);
signIn('owner-a');response=await api.POST(request({opacity:0,size:10}));assert.equal(response.status,200);saved=(await (await api.GET()).json()).settings;assert.equal(saved.opacity,0);assert.equal(saved.size,10);assert.equal(saved.imageName,'logo.png');assert.equal(objects.size,1);
assert.equal((await api.POST(request({size:101}))).status,400);assert.equal((await api.POST(request({opacity:-1}))).status,400);assert.equal((await api.POST(request({orientation:'invalid'}))).status,400);assert.equal((await api.POST(request({},undefined,'https://other.test'))).status,403);
assert.equal((await api.POST(request({},new File(['<script>bad</script>'],'logo.png',{type:'image/png'})))).status,400);
assert.equal((await api.POST(request({},new File([new Uint8Array(3*1024*1024+1)],'huge.png',{type:'image/png'})))).status,413);
failWrite=true;response=await api.POST(request({},new File([png],'replacement.png',{type:'image/png'})));assert.equal(response.status,503);assert.equal(objects.size,1);assert.equal((await imageApi.GET()).status,200);failWrite=false;
response=await api.POST(request({removeImage:true}));assert.equal(response.status,200);assert.equal((await response.json()).settings.imageUrl,null);assert.equal(objects.size,0);assert.equal((await imageApi.GET()).status,404);
sqlite.close();console.log('Passed: private watermark settings, upload/read isolation, orientation/opacity/size persistence, invalid images, limits, failed-save cleanup and removal.');
