import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {Plus,Trash2,ArrowUp,ArrowDown,Save,Loader2,ListOrdered} from 'lucide-react';
import {Field} from '@/shared/components/Common';
import {ModuleLink,useModuleNavigation} from '@/shared/navigation/ModuleNavigation';
import {notifications,useConfirmation} from '@/shared/feedback';
import {contractTypesHref,contractTypeHref} from '../utils/typeNavigation';
import {TypeApiError} from '../services/typeApi';
import {useContractTypesMutation} from '../hooks/useContractTypes';
import type {ContractType,ContractStage} from '../types';
export function ContractTypeForm({type,initialName=''}:{type?:ContractType;initialName?:string}){
  const mutation=useContractTypesMutation();
  const [name,setName]=useState(type?.name||initialName);const [stages,setStages]=useState<ContractStage[]>(type?.stages||[]);const [error,setError]=useState('');const [saving,setSaving]=useState(false);const [auth,setAuth]=useState(false);const mounted=useRef(true);const {navigate}=useModuleNavigation();const confirm=useConfirmation();
  useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
  const move=(index:number,delta:number)=>setStages(current=>{const result=[...current];[result[index],result[index+delta]]=[result[index+delta],result[index]];return result;});
  const removeStage=async(index:number)=>{const stage=stages[index];const accepted=await confirm({title:'Remover esta etapa?',description:`A etapa “${stage.name||String(index+1)}” será retirada do tipo de contrato quando você salvar.`,confirmLabel:'Remover etapa',tone:'destructive'});if(accepted)setStages(current=>current.filter(item=>item.id!==stage.id));};
  return <form className="client-form contract-type-form" onSubmit={async event=>{event.preventDefault();if(saving)return;setError('');try{setSaving(true);const saved=await mutation.mutateAsync({input:{name,stages},id:type?.id});if(mounted.current){if(type)notifications.updated('O tipo de contrato e suas etapas foram atualizados.');else notifications.created('O tipo de contrato foi cadastrado.');navigate(contractTypeHref(saved.id));}}catch(error){if(mounted.current){setError((error as Error).message);if(error instanceof TypeApiError&&error.status===401)setAuth(true);}}finally{if(mounted.current)setSaving(false);}}}>
    <fieldset disabled={saving} className="company-fieldset"><Field label="Nome do tipo de contrato"><input required minLength={2} maxLength={150} value={name} onChange={event=>setName(event.target.value)} placeholder="Ex.: Contrato manual"/></Field><div className="contract-stage-heading"><div><h3><ListOrdered size={18}/>Etapas deste tipo</h3><p>Defina as etapas na ordem em que devem acontecer.</p></div><span>{stages.length} etapa{stages.length!==1?'s':''}</span></div>
    {!stages.length?<div className="contract-stage-empty">Nenhuma etapa cadastrada. Adicione as etapas deste tipo de contrato.</div>:<ol className="contract-stage-list">{stages.map((stage,index)=><li key={stage.id} className="contract-stage-row"><span className="contract-stage-number" aria-hidden="true">{String(index+1).padStart(2,'0')}</span><input aria-label={'Nome da etapa '+(index+1)} value={stage.name} maxLength={120} required placeholder={'Nome da etapa '+(index+1)} onChange={event=>setStages(current=>current.map(item=>item.id===stage.id?{...item,name:event.target.value}:item))}/><div className="contract-stage-actions"><button className="icon-btn" type="button" disabled={index===0} onClick={()=>move(index,-1)} aria-label={'Mover etapa '+(index+1)+' para cima'}><ArrowUp size={15}/></button><button className="icon-btn" type="button" disabled={index===stages.length-1} onClick={()=>move(index,1)} aria-label={'Mover etapa '+(index+1)+' para baixo'}><ArrowDown size={15}/></button><button type="button" className="icon-btn" onClick={()=>{void removeStage(index);}} aria-label={'Remover etapa '+(index+1)}><Trash2 size={15}/></button></div></li>)}</ol>}
    <button type="button" className="contract-add-stage" disabled={stages.length>=50} onClick={()=>setStages(current=>[...current,{id:crypto.randomUUID(),name:''}])}><Plus size={16}/>Adicionar etapa</button></fieldset>
    {error&&<p className="form-error" role="alert">{error}</p>}{auth&&<Link className="client-signin" href="/login?returnTo=%2Fcadastro%3Fsecao%3Dcontratos" target="_top">Entrar</Link>}<div className="form-actions"><ModuleLink className="btn" href={contractTypesHref} onClick={event=>{if(saving)event.preventDefault();}} aria-disabled={saving}>Cancelar</ModuleLink><button className="btn company-primary" disabled={saving}>{saving?<Loader2 size={16} className="animate-spin"/>:<Save size={16}/>} {saving?'Salvando…':type?'Salvar alterações':'Cadastrar tipo'}</button></div>
  </form>;
}
