import type {ContractStage} from '@/modules/cadastro/contratos/types';
export const contractStatuses=['Ativo','Concluído','Cancelado'] as const;
export type ContractStatus=typeof contractStatuses[number];
export const contractAtrPriceTypes=['gross','net'] as const;
export type ContractAtrPriceType=typeof contractAtrPriceTypes[number];
export const contractAtrPeriodTypes=['monthly','accumulated'] as const;
export type ContractAtrPeriodType=typeof contractAtrPeriodTypes[number];
export type ContractBucket='open'|'finished';
export type ContractFilters={companyId:string;bucket:ContractBucket;search:string;from:string;to:string};
export type ContractInput={title:string;contractNumber:string;companyId:string;clientId:string;typeId:string;status:ContractStatus;startDate:string;endDate:string;contractedVolume:string;atrPriceType:ContractAtrPriceType;atrPeriodType:ContractAtrPeriodType;value:string;notes:string};
export type ContractLoadInput={loadedAt:string;farmId:string;plotId:string;volume:string;atr:string;document:string;notes:string};
export type ContractLoad=ContractLoadInput&{id:string;contractId:string;atrReferenceMonth:string;farmName:string;plotName:string;createdAt:string;updatedAt:string};
export type ContractLoadFilters={search:string;from:string;to:string;groupBy:'month'|'farm'|'none'};
export type ContractPricedLoad=ContractLoad&{atrQuote:string;grossAmount:string;discountAmount:string;netAmount:string;billingPending:boolean};
export type ContractLoadGroup={key:string;label:string;loadCount:number;volume:string;averageAtr:string;loads:ContractPricedLoad[]};
export type ContractLoadsData={filters:ContractLoadFilters;summary:{loadCount:number;volume:string;farmCount:number;plotCount:number;averageAtr:string;firstLoadedAt:string;lastLoadedAt:string;grossAmount:string;discountAmount:string;netAmount:string;billingPending:boolean};groups:ContractLoadGroup[]};
export type ContractMonthlyRow={month:string;atrReferenceMonth:string;loadedVolume:string;averageLoadAtr:string;atrQuote:string;billingAmount:string;billingPending:boolean;expenseAmount:string;expensesPending:boolean;resultAmount:string};
export type ContractMonthlyTotals={contractedVolume:string;loadedVolume:string;remainingVolume:string;averageLoadAtr:string;billingAmount:string;billingPending:boolean;pendingQuoteMonths:number;expenseAmount:string;expensesPending:boolean;resultAmount:string};
export type ContractMonthlySummary={criteria:{atrPriceType:ContractAtrPriceType;atrPeriodType:ContractAtrPeriodType};months:ContractMonthlyRow[];totals:ContractMonthlyTotals};
export type ContractAtrQuoteSummary={average:string;pending:boolean;loadedMonths:string[];referenceMonths:string[]};
export type BillingContract=ContractInput&{
 id:string;companyName:string;companyCnpj:string;clientName:string;clientCnpj:string;typeName:string;stages:ContractStage[];
 loadedVolume:string;remainingVolume:string;averageAtr:string;billingAmount:string;billingPending:boolean;monthlySummary?:ContractMonthlySummary;financialSummary?:ContractFinancialSummary;financialTotals?:ContractFinancialMetrics;atrQuoteSummary?:ContractAtrQuoteSummary;loads?:ContractLoad[];createdAt:string;updatedAt:string;
};
export type ContractListSummary=ContractFinancialMetrics&{pendingContractCount:number};
export type ContractListData={contracts:BillingContract[];counts:{open:number;finished:number};total:number;summary:ContractListSummary};
export type ContractPaymentKind='advance'|'receipt';
export type ContractPaymentInput={requestId:string;kind:ContractPaymentKind;receivedAt:string;referenceMonth:string;amount:string;document:string;notes:string};
export type ContractPayment=ContractPaymentInput&{id:string;revision:number};
export type ContractDiscountInput={requestId:string;title:string;ratePerTon:string;months:string[];notes:string};
export type ContractDiscountMonthlyRow={month:string;loadedVolume:string;amount:string};
export type ContractDiscount=ContractDiscountInput&{id:string;revision:number;loadedVolume:string;amount:string;monthlyBreakdown:ContractDiscountMonthlyRow[]};
export type ContractFinancialMetrics={loadedVolume:string;averageAtr:string;grossAmount:string;billingPending:boolean;discountAmount:string;netAmount:string;advanceAmount:string;receiptAmount:string;receivedAmount:string;pendingAmount:string;creditAmount:string};
export type ContractFinancialSummary={months:(ContractFinancialMetrics&{month:string})[];totals:ContractFinancialMetrics;emptyMonth:ContractFinancialMetrics;payments:ContractPayment[];discounts:ContractDiscount[]};
