import {useState} from 'react';
import {KeyRound,Loader2,Pencil,Plus,RefreshCw,ShieldCheck,Trash2} from 'lucide-react';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {notifications,useConfirmation} from '@/shared/feedback';
import {useAccessProfiles} from '../hooks/useAccessProfiles';
import {AccessProfileForm} from '../forms/AccessProfileForm';
import type {AccessProfile} from '../types';

export function PerfisAcessoPage(){
  const model=useAccessProfiles();const confirm=useConfirmation();const [open,setOpen]=useState(false);const [busy,setBusy]=useState(false);const [selected,setSelected]=useState<AccessProfile>();const [actionId,setActionId]=useState('');const [actionError,setActionError]=useState('');
  const begin=(profile?:AccessProfile)=>{setSelected(profile);setBusy(false);setOpen(true);};const close=()=>{setOpen(false);setSelected(undefined);};
  const remove=async(profile:AccessProfile)=>{if(profile.isSystem||profile.userCount)return;const accepted=await confirm({title:`Excluir o perfil “${profile.name}”?`,description:'Esta ação remove definitivamente o perfil de acesso.',confirmLabel:'Excluir perfil',tone:'destructive'});if(!accepted)return;setActionId(profile.id);setActionError('');try{await model.remove(profile.id);notifications.deleted('O perfil de acesso foi excluído.');}catch(caught){const message=(caught as Error).message;setActionError(message);notifications.error(message);}finally{setActionId('');}};
  return <section className="companies-section"><div className="companies-heading"><div><h2>Perfis de acesso</h2><p>Defina o que cada grupo de usuários pode consultar e alterar.</p></div>{!model.authRequired&&<button className="btn company-primary" onClick={()=>begin()} disabled={model.loading||!!model.error}><Plus size={17}/>Cadastrar perfil</button>}</div>
    {actionError&&<p className="form-error" role="alert">{actionError}</p>}
    {model.loading?<div className="client-loading" role="status"><Loader2 className="animate-spin" size={20}/>Carregando perfis…</div>:model.authRequired?<div className="company-empty"><span className="company-empty-icon"><KeyRound size={26}/></span><h3>Entre para gerenciar perfis</h3><p>Somente pessoas autorizadas podem acessar esta configuração.</p></div>:model.error?<div className="company-empty" role="alert"><h3>Não foi possível carregar</h3><p>{model.error}</p><button className="btn" onClick={model.reload}><RefreshCw size={16}/>Tentar novamente</button></div>:!model.profiles.length?<div className="company-empty"><span className="company-empty-icon"><ShieldCheck size={27}/></span><h3>Cadastre o primeiro perfil</h3><p>Agrupe permissões para aplicar o mesmo nível de acesso a vários usuários.</p><button className="btn company-primary" onClick={()=>begin()}><Plus size={16}/>Cadastrar perfil</button></div>:<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{model.profiles.map(profile=><article key={profile.id} className="config-section-card"><span className="config-section-icon"><ShieldCheck size={19}/></span><h3 className="text-sm font-semibold">{profile.name}</h3><p>{profile.description||'Sem descrição.'}</p><p>{profile.permissions.length} permissão{profile.permissions.length!==1?'ões':''} · {profile.userCount} usuário{profile.userCount!==1?'s':''}</p><div className="mt-4 flex items-center gap-2 border-t pt-4">{profile.isSystem?<span className="status status-ativo">Perfil do sistema</span>:<><button type="button" className="btn small" onClick={()=>begin(profile)} disabled={!!actionId}><Pencil size={14}/>Editar</button><button type="button" className="icon-btn" aria-label={`Excluir perfil ${profile.name}`} title={profile.userCount?'Reatribua os usuários antes de excluir':'Excluir perfil'} onClick={()=>{void remove(profile);}} disabled={!!actionId||profile.userCount>0}>{actionId===profile.id?<Loader2 className="animate-spin" size={15}/>:<Trash2 size={15}/>}</button></>}</div></article>)}</div>}
    <Dialog open={open} onOpenChange={value=>{if(!value&&!busy)close();}}><DialogContent className="form-modal max-w-3xl" onEscapeKeyDown={event=>{if(busy)event.preventDefault();}} onPointerDownOutside={event=>{if(busy)event.preventDefault();}}><DialogHeader><DialogTitle>{selected?'Editar perfil de acesso':'Cadastrar perfil de acesso'}</DialogTitle><DialogDescription>Escolha um nome e marque as ações permitidas.</DialogDescription></DialogHeader><AccessProfileForm key={selected?.id??'new'} profile={selected} onBusy={setBusy} onClose={close} onSave={model.save}/></DialogContent></Dialog>
  </section>;
}
