import {Bar,BarChart,CartesianGrid,Legend,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import type {ContractSummaryMonth} from '../../utils/contractMonthlyPresentation';
import {formatContractBilling,formatContractMonth,formatContractVolume} from '../../utils/contractFormat';

export function ContractMonthlyCharts({months}:{months:ContractSummaryMonth[]}){
 const data=months.map(item=>({month:formatContractMonth(item.month),volume:Number(item.loadedVolume),billing:item.billingPending?null:Number(item.billingAmount),received:item.finance?Number(item.finance.receivedAmount):null}));
 const volumeLabel=(value:number)=>value>=1000?`${new Intl.NumberFormat('pt-BR',{maximumFractionDigits:1}).format(value/1000)} mil`:new Intl.NumberFormat('pt-BR',{maximumFractionDigits:0}).format(value);
 const moneyLabel=(value:number)=>value>=1000000?`R$ ${new Intl.NumberFormat('pt-BR',{maximumFractionDigits:1}).format(value/1000000)} mi`:value>=1000?`R$ ${new Intl.NumberFormat('pt-BR',{maximumFractionDigits:0}).format(value/1000)} mil`:`R$ ${new Intl.NumberFormat('pt-BR',{maximumFractionDigits:0}).format(value)}`;
 return <div className="contract-monthly-charts">
  <section><header><h4>Quantidade carregada por mês</h4><span>Toneladas entregues</span></header><div className="contract-monthly-chart" role="img" aria-label={'Quantidade carregada por mês: '+months.map(item=>`${formatContractMonth(item.month)} ${formatContractVolume(item.loadedVolume)}`).join(', ')}><ResponsiveContainer width="100%" height="100%"><BarChart data={data} margin={{top:10,right:10,left:-8,bottom:0}}><CartesianGrid vertical={false} stroke="#e7eee9" strokeDasharray="4 5"/><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{fontSize:11,fill:'#788b7e'}}/><YAxis tickFormatter={volumeLabel} axisLine={false} tickLine={false} tick={{fontSize:10,fill:'#8a9990'}}/><Tooltip formatter={value=>[formatContractVolume(String(Number(value))), 'Quantidade']} contentStyle={{borderRadius:9,borderColor:'#dfe8e2',fontSize:12}}/><Bar dataKey="volume" fill="#54a873" radius={[5,5,0,0]} maxBarSize={34}/></BarChart></ResponsiveContainer></div></section>
  <section><header><h4>Faturado e recebido por mês</h4><span>Entregas e entradas financeiras</span></header><div className="contract-monthly-chart" role="img" aria-label={'Faturado e recebido por mês: '+months.map(item=>`${formatContractMonth(item.month)}: faturado ${formatContractBilling(item.billingAmount,item.billingPending)}, recebido ${item.finance?formatContractBilling(item.finance.receivedAmount):'indisponível'}`).join(', ')}><ResponsiveContainer width="100%" height="100%"><BarChart data={data} margin={{top:10,right:10,left:2,bottom:0}}><CartesianGrid vertical={false} stroke="#e7eee9" strokeDasharray="4 5"/><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{fontSize:11,fill:'#788b7e'}}/><YAxis tickFormatter={moneyLabel} axisLine={false} tickLine={false} tick={{fontSize:10,fill:'#8a9990'}}/><Tooltip formatter={(value,name)=>[formatContractBilling(String(Number(value))), String(name)]} contentStyle={{borderRadius:9,borderColor:'#dfe8e2',fontSize:12}}/><Legend iconType="circle" wrapperStyle={{fontSize:10}}/><Bar dataKey="billing" name="Faturado bruto" fill="#2f8052" radius={[5,5,0,0]} maxBarSize={28}/><Bar dataKey="received" name="Total recebido" fill="#4c81a5" radius={[5,5,0,0]} maxBarSize={28}/></BarChart></ResponsiveContainer></div></section>
 </div>;
}
