export type RequestStatus = 'pending' | 'approved' | 'rejected';
export type RequestWorkflowStatus = 'open' | 'in_progress' | 'finished' | 'rejected';
export type RequestItem = {description: string; application: string};
export type RequestFile = {id: string; bucket: string; path: string; fileName: string; contentType: string; size: number};
export type RequestSigningMode = 'registered' | 'manual';
export type RequestSignature = {id: string; userId: string | null; name: string; filePath: string | null};
export type RequestActor = {userId: string | null; name: string; signatureId: string; signaturePath: string | null; signingMode: RequestSigningMode; signatureHash: string | null};
export type RequestDecision = RequestActor & {userId: string; at: string; reason: string};
export type RequestHistory = {id: string; action: string; actorId: string; actorName: string; signaturePath: string | null; at: string; reason: string};
export type RequestDetails = {serviceValue: string | null; returnDate: string | null};
export type RequestComplement = RequestDetails & {id: string; version: number; attachmentIds: string[]; actorId: string; actorName: string; at: string; hash: string; recordedStatus?: 'pending' | 'approved'};
export type RequestComplementInput = RequestDetails & {id: string; operationId: string; expectedComplementId: string | null; attachmentIds: string[]};
export type ServiceRequest = {
  id: string;
  documentHash: string;
  template: DocumentTemplate;
  number: number;
  status: RequestStatus;
  workflowStatus?: RequestWorkflowStatus;
  canComplete?: boolean;
  completion?: {at: string; userId: string; name: string} | null;
  companyName: string;
  companyAddress: string;
  providerId: string | null;
  provider: ServiceProvider | null;
  items: RequestItem[];
  serviceValue: string | null;
  returnDate: string | null;
  notes: string;
  createdAt: string;
  createdBy: {userId: string; name: string};
  requester: RequestActor;
  decision: RequestDecision | null;
  decisionComplementHash?: string | null;
  attachments: RequestFile[];
  history: RequestHistory[];
  canDecide: boolean;
  canComplement: boolean;
  currentDetails: RequestDetails;
  complements: RequestComplement[];
};
export type RequestFilters = {
  search: string;
  dateFrom: string;
  dateTo: string;
  requesterId: string;
  tab: 'pending' | 'in_progress' | 'finished';
  page: number;
  pageSize: number;
};
export type RequestCollection = {
  items: ServiceRequest[];
  total: number;
  page: number;
  pageSize: number;
  counts: {pending: number; inProgress?: number; finished: number};
};
export type RequestOptions = {
  requesters: {id: string; name: string}[];
  requesterSignatures: RequestSignature[];
  managerSignature: RequestSignature | null;
  canCreate: boolean;
  canDecide: boolean;
  actorId: string;
};
export type RequestInput = {
  requestId: string;
  requesterSignatureId: string;
  requesterSigningMode: RequestSigningMode;
  providerId: string;
  items: RequestItem[];
  serviceValue: string | null;
  returnDate: string | null;
  notes: string;
  attachmentIds: string[];
};
export type RequestDecisionInput = {id: string; decision: 'approved' | 'rejected'; reason: string; managerSigningMode: RequestSigningMode; expectedComplementId?: string | null};
export type RequestExecution = {actorId: string; signal: AbortSignal};
import type {DocumentTemplate} from '@/modules/cadastro/modelos-documentos/types';
import type {ServiceProvider} from '@/modules/cadastro/prestadores/types';
