'use client';

import {useMemo,useState} from 'react';
import {BadgeInfo,Factory,Loader2,Pencil,Plus,RefreshCw,Save,Search,Trash2,Truck} from 'lucide-react';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {Field} from '@/shared/components/Common';
import {notifications,useConfirmation} from '@/shared/feedback';
import {ModuleLink} from '@/shared/navigation/ModuleNavigation';
import {useFleet,useFleetMutations} from '../hooks/useFleet';
import {emptyFleetVehicle,type FleetVehicle,type FleetVehicleInput} from '../types';
import '../styles.css';

export function FrotaPage(){
 const query=useFleet();const mutations=useFleetMutations();const confirm=useConfirmation();const [editing,setEditing]=useState<FleetVehicle|null|undefined>(undefined);const [search,setSearch]=useState('');
 const vehicles=useMemo(()=>query.data?.vehicles??[],[query.data]);const canManage=query.data?.canManage??false;
 const filtered=useMemo(()=>{const value=search.trim().toLocaleLowerCase('pt-BR');return vehicles.filter(vehicle=>!value||`${vehicle.internalCode} ${vehicle.model} ${vehicle.brand} ${vehicle.description}`.toLocaleLowerCase('pt-BR').includes(value));},[search,vehicles]);
 const remove=async(vehicle:FleetVehicle)=>{const accepted=await confirm({title:'Excluir veículo?',description:`O veículo “${vehicle.internalCode} · ${vehicle.model}” será removido da frota.`,confirmLabel:'Excluir',tone:'destructive'});if(!accepted)return;try{await mutations.remove(vehicle.id);notifications.deleted('Veículo removido da frota.');}catch(reason){notifications.error((reason as Error).message||'Não foi possível excluir o veículo.');}};
 const addButton=canManage?<button type="button" className="btn company-primary" onClick={()=>setEditing(null)}><Plus size={17}/>Cadastrar veículo</button>:null;
 return <section className="fleet-workspace"><nav className="client-breadcrumb farm-breadcrumb" aria-label="Caminho de navegação"><ModuleLink href="/cadastro">Cadastros</ModuleLink><span aria-hidden="true">›</span><span aria-current="page">Frota</span></nav><div className="companies-heading"><div><h2>Frota</h2><p>Cadastre os veículos por código interno, modelo e marca.</p></div>{addButton}</div>
  {!query.loading&&!query.error&&!!vehicles.length&&<div className="farm-toolbar"><label className="local-search"><Search size={16}/><span className="sr-only">Buscar veículo</span><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Buscar código, modelo, marca ou descrição…"/></label><span>{filtered.length} de {vehicles.length}</span></div>}
  {query.loading?<div className="client-loading" role="status"><Loader2 size={20} className="animate-spin"/>Carregando frota…</div>:query.error?<div className="company-empty" role="alert"><h3>Não foi possível carregar a frota</h3><p>{query.error}</p><button type="button" className="btn" onClick={()=>void query.reload()}><RefreshCw size={16}/>Tentar novamente</button></div>:!vehicles.length?<div className="company-empty"><span className="company-empty-icon"><Truck size={25}/></span><h3>Nenhum veículo cadastrado</h3><p>Cadastre o primeiro veículo da frota com seu código interno.</p>{addButton}</div>:!filtered.length?<div className="company-empty"><span className="company-empty-icon"><Search size={25}/></span><h3>Nenhum veículo encontrado</h3><p>Ajuste a busca para localizar outro cadastro.</p><button type="button" className="btn" onClick={()=>setSearch('')}>Limpar busca</button></div>:<div className="fleet-grid">{filtered.map(vehicle=><article className="fleet-card" key={vehicle.id}><header><span><Truck size={19}/></span>{canManage&&<div><button type="button" className="icon-btn" aria-label={`Editar ${vehicle.model}`} onClick={()=>setEditing(vehicle)}><Pencil size={15}/></button><button type="button" className="icon-btn" aria-label={`Excluir ${vehicle.model}`} onClick={()=>void remove(vehicle)}><Trash2 size={15}/></button></div>}</header><small>Código interno</small><strong>{vehicle.internalCode}</strong><h3>{vehicle.model}</h3><p className="fleet-brand"><Factory size={14}/>{vehicle.brand}</p><p className="fleet-description"><BadgeInfo size={14}/><span>{vehicle.description||'Sem descrição'}</span></p></article>)}</div>}
  {editing!==undefined&&<FleetForm vehicle={editing??undefined} onClose={()=>setEditing(undefined)} onSave={async input=>{const saved=await mutations.save(input);notifications[input.id?'updated':'created'](input.id?'Veículo atualizado com sucesso.':'Veículo cadastrado com sucesso.');setEditing(undefined);return saved;}}/>}
 </section>;
}

function FleetForm({vehicle,onClose,onSave}:{vehicle?:FleetVehicle;onClose:()=>void;onSave:(input:FleetVehicleInput)=>Promise<FleetVehicle>}){
 const [form,setForm]=useState<FleetVehicleInput>(vehicle?{id:vehicle.id,internalCode:vehicle.internalCode,model:vehicle.model,brand:vehicle.brand,description:vehicle.description}:{...emptyFleetVehicle});const [saving,setSaving]=useState(false);const [error,setError]=useState('');
 const change=(key:keyof FleetVehicleInput,value:string)=>{setForm(current=>({...current,[key]:value}));setError('');};
 const submit=async(event:React.FormEvent)=>{event.preventDefault();if(!form.internalCode.trim()||!form.model.trim()||!form.brand.trim()){setError('Preencha código interno, modelo e marca.');return;}setSaving(true);setError('');try{await onSave(form);}catch(reason){const message=(reason as Error).message||'Não foi possível salvar o veículo.';setError(message);notifications.error(message);setSaving(false);}};
 return <Dialog open onOpenChange={open=>{if(!open&&!saving)onClose();}}><DialogContent className="form-modal fleet-modal" showCloseButton={!saving} onEscapeKeyDown={event=>{if(saving)event.preventDefault();}} onPointerDownOutside={event=>{if(saving)event.preventDefault();}}><DialogHeader><DialogTitle>{vehicle?'Editar veículo':'Cadastrar veículo'}</DialogTitle><DialogDescription>Informe a identificação do veículo da frota.</DialogDescription></DialogHeader><form onSubmit={event=>void submit(event)}><fieldset disabled={saving}><div className="form-grid"><Field label="Código interno *"><input autoFocus value={form.internalCode} maxLength={60} onChange={event=>change('internalCode',event.target.value)}/></Field><Field label="Marca *"><input value={form.brand} maxLength={100} placeholder="Ex.: Volvo" onChange={event=>change('brand',event.target.value)}/></Field></div><Field label="Modelo *"><input value={form.model} maxLength={150} placeholder="Ex.: FH 540 6x4" onChange={event=>change('model',event.target.value)}/></Field><Field label="Descrição (opcional)"><textarea rows={4} maxLength={1000} value={form.description} placeholder="Características, placa ou observações" onChange={event=>change('description',event.target.value)}/></Field></fieldset>{error&&<p className="form-error" role="alert">{error}</p>}<div className="form-actions"><button type="button" className="btn" disabled={saving} onClick={onClose}>Cancelar</button><button type="submit" className="btn company-primary" disabled={saving}>{saving?<Loader2 size={16} className="animate-spin"/>:<Save size={16}/>} {saving?'Salvando…':vehicle?'Salvar alterações':'Cadastrar veículo'}</button></div></form></DialogContent></Dialog>;
}
