'use client';
import {useState} from 'react';
import {ArrowUpRight,Banknote,CalendarRange,Download,FileChartColumn,FileText,Landmark,Leaf,MapPinned,Minus,ReceiptText,RefreshCw,Sprout,Target,TrendingDown,TrendingUp,Truck} from 'lucide-react';
import {ModuleLink} from '@/shared/navigation/ModuleNavigation';
import {BillingQueryState} from '@/shared/components/BillingQueryState';
import {dateLabel,decimalLabel,localDay,moneyLabel} from '@/shared/utils/presentation';
import {useExecutiveSummary} from '../hooks/useSummary';
import {FarmVolumeChart,FinancialComposition,FinancialEvolution} from './SummaryCharts';
import {SummaryExportDialog} from './SummaryExportDialog';
import {MonthlyOperationsPanel,PerformanceRankings,PlanningPerformanceTable,Progress} from './SummaryOperational';
import '../styles.css';

type Range={from:string;to:string};
const shiftDay=(day:string,amount:number)=>{const date=new Date(`${day}T12:00:00`);date.setDate(date.getDate()+amount);return localDay(date);};
const defaultRange=():Range=>{const to=localDay();return {from:shiftDay(to,-364),to};};
const rangeDays=({from,to}:Range)=>Math.round((new Date(`${to}T12:00:00`).getTime()-new Date(`${from}T12:00:00`).getTime())/86400000)+1;

export function ResumoPage(){
 const [range,setRange]=useState<Range>(defaultRange),[draft,setDraft]=useState<Range>(defaultRange),[exporting,setExporting]=useState(false);
 const model=useExecutiveSummary(range.from,range.to),data=model.data,days=rangeDays(draft);
 const contractPerformance=new Map((data?.contractPerformance??[]).map(item=>[item.id,item]));
 const invalid=!draft.from||!draft.to||days<1||days>1827;
 const preset=(amount:number)=>{const to=localDay(),next={from:shiftDay(to,-amount+1),to};setDraft(next);setRange(next);};
 return <section className="summary-page">
  <div className="summary-heading"><div><div className="eyebrow">VISÃO EXECUTIVA</div><h2>Resumo gerencial</h2><p>Contratos, faturamento e operação agrícola de {model.company?.name||'sua empresa'} em uma única leitura.</p></div>{data&&<button className="btn company-primary summary-export" type="button" onClick={()=>setExporting(true)}><Download size={16}/>Exportar PDF completo</button>}</div>
  <div className="summary-filter" aria-label="Período do resumo"><div className="summary-filter-title"><span><CalendarRange size={18}/></span><div><strong>Período de análise</strong><small>365 dias por padrão · máximo de 5 anos</small></div></div><div className="summary-presets" aria-label="Períodos rápidos"><button type="button" onClick={()=>preset(30)}>30 dias</button><button type="button" onClick={()=>preset(90)}>90 dias</button><button type="button" className={rangeDays(range)===365?'active':''} onClick={()=>preset(365)}>365 dias</button><button type="button" onClick={()=>{const to=localDay(),next={from:`${to.slice(0,4)}-01-01`,to};setDraft(next);setRange(next);}}>Ano atual</button></div><div className="summary-date-fields"><label>De<input type="date" min="1900-01-01" max={draft.to||'9999-12-31'} value={draft.from} onChange={event=>setDraft(value=>({...value,from:event.target.value}))}/></label><span>até</span><label>Até<input type="date" min={draft.from||'1900-01-01'} max="9999-12-31" value={draft.to} onChange={event=>setDraft(value=>({...value,to:event.target.value}))}/></label><button type="button" className="btn" disabled={invalid||(draft.from===range.from&&draft.to===range.to)} onClick={()=>setRange(draft)}>Aplicar</button></div>{invalid&&<p className="summary-filter-error" role="alert">Escolha um período entre 1 dia e 5 anos.</p>}</div>
  <BillingQueryState {...model}/>
  {data&&!model.errorMessage&&<div aria-busy={model.isFetching}>
   <section className="summary-hero"><div className="summary-hero-main"><span>FATURAMENTO LÍQUIDO · {dateLabel(data.range.from)} A {dateLabel(data.range.to)}</span><h3>{moneyLabel(data.totals.netAmount)}</h3><ChangeBadge value={data.comparison.netChangePercent} label="período anterior"/><p>Valor das cargas após descontos. Pendências de ATR ou cotação continuam como “A apurar”.</p></div><div className="summary-hero-divider"/><div className="summary-hero-stat"><Truck/><span>Volume carregado</span><strong>{decimalLabel(data.totals.loadedVolume)} <small>t</small></strong><ChangeBadge value={data.comparison.volumeChangePercent} label="volume"/></div><div className="summary-hero-stat"><FileText/><span>Movimentação</span><strong>{data.totals.loadCount} <small>cargas</small></strong><p>{data.totals.activeContractCount} contratos ativos</p></div>{model.isFetching&&<div className="summary-refresh" role="status"><RefreshCw className="animate-spin" size={14}/>Atualizando</div>}</section>
   <dl className="summary-kpis"><Metric icon={Banknote} label="Faturamento bruto" value={moneyLabel(data.totals.grossAmount)} detail={data.totals.billingPending?`${data.totals.pendingLoadCount} carga(s) a apurar`:'Valor das entregas'}/><Metric icon={ReceiptText} label="Descontos" value={moneyLabel(data.totals.discountAmount)} detail="Acordos aplicados às cargas" tone="warning"/><Metric icon={Landmark} label="Entradas em caixa" value={moneyLabel(data.totals.receivedAmount)} detail={`${moneyLabel(data.totals.advanceAmount)} adiantado`}/><Metric icon={TrendingUp} label="Diferença do recorte" value={moneyLabel(data.totals.pendingAmount)} detail="Líquido menos entradas nas datas"/></dl>
   {data.totals.billingPending&&<div className="summary-notice" role="status"><strong>Existem valores financeiros incompletos.</strong><span>{data.totals.pendingLoadCount} carregamento(s) aguardam ATR ou cotação. O painel não transforma essas pendências em zero.</span></div>}
   <div className="summary-analytics"><FinancialEvolution data={data.months}/><FinancialComposition totals={data.totals}/></div>
   {data.operationalTotals&&data.monthlyOperations&&<MonthlyOperationsPanel data={data}/>}
   <section className="summary-block"><div className="summary-block-heading"><div><span className="summary-kicker"><MapPinned size={14}/>OPERAÇÃO DA EMPRESA</span><h3>De onde veio a produção</h3><p>Fazendas e talhões com carregamentos no período selecionado.</p></div><div className="summary-inline-stats"><span><strong>{data.totals.farmCount}</strong> fazendas movimentadas</span><span><strong>{data.totals.plotCount}</strong> talhões movimentados</span></div></div><div className="summary-operation-grid"><FarmVolumeChart farms={data.farms}/><div className="summary-panel summary-registry"><header className="summary-panel-heading"><div><span className="summary-kicker"><Leaf size={14}/>CADASTRO AGRÍCOLA ATUAL</span><h3>Estrutura do workspace</h3><p>Retrato atual, independente da empresa ativa.</p></div></header><dl><div><dt>Fazendas cadastradas</dt><dd>{data.agriculture.registeredFarmCount}</dd></div><div><dt>Talhões cadastrados</dt><dd>{data.agriculture.registeredPlotCount}</dd></div><div><dt>Área total</dt><dd>{decimalLabel(data.agriculture.farmAreaHa)} ha</dd></div><div><dt>Área mapeada</dt><dd>{decimalLabel(data.agriculture.plotAreaHa)} ha</dd></div></dl></div></div></section>
   {data.farmPerformance&&data.plotPerformance&&<PerformanceRankings data={data}/>}
   <section className="summary-block summary-planning"><div className="summary-block-heading"><div><span className="summary-kicker"><Target size={14}/>PLANEJAMENTO DO WORKSPACE</span><h3>{data.planning.periodName||'Metas e execução agrícola'}</h3><p>{data.planning.periodName?`Safra em foco · acumulado até ${dateLabel(data.planning.progressAsOf)}. Uma única safra é usada para evitar somar metas sobrepostas.`:'Nenhuma safra cruza o período selecionado.'}</p></div><ModuleLink href="/planejamento" className="text-link">Abrir planejamento<ArrowUpRight size={16}/></ModuleLink></div><div className="summary-planning-grid"><ProgressCard icon={Sprout} title="Plantio" percent={data.planning.plantingPercent} actual={`${decimalLabel(data.planning.plantedAreaHa)} ha`} target={`${decimalLabel(data.planning.targetAreaHa)} ha`} detail={`${decimalLabel(data.planning.allocatedAreaHa)} ha distribuídos`}/><ProgressCard icon={Truck} title="Colheita" percent={data.planning.harvestPercent} actual={`${decimalLabel(data.planning.harvestedTons)} t`} target={`${decimalLabel(data.planning.harvestTargetTons)} t`} detail="Cargas dos talhões da safra"/><div className="summary-panel summary-management"><header><div><span className="summary-kicker"><Leaf size={14}/>MANEJO REALIZADO</span><h3>{decimalLabel(data.planning.managedAreaHa)} ha</h3><p>{data.planning.managementEventCount} ocorrências na safra em foco</p></div></header>{data.management.length?<ol>{data.management.slice(0,5).map(item=><li key={item.id}><span><i/>{item.name}</span><strong>{decimalLabel(item.areaHa)} ha</strong><small>{item.eventCount} lançamento(s)</small></li>)}</ol>:<div className="summary-compact-empty">Nenhum manejo registrado para a safra em foco.</div>}</div></div><PlanningPerformanceTable farms={data.planningPerformance?.farms??[]} plots={data.planningPerformance?.plots??[]}/></section>
   <section className="summary-block"><div className="summary-block-heading"><div><span className="summary-kicker"><FileChartColumn size={14}/>CONTRATOS E RESULTADOS</span><h3>Contratos da empresa ativa</h3><p>Volume do período, ATR ponderado e cumprimento da quantidade contratada.</p></div><div className="summary-statuses">{data.contractStatus.map(item=><span key={item.status}>{item.status}<strong>{item.count}</strong></span>)}</div></div>{data.contracts.length?<div className="summary-table-wrap"><table className="summary-table summary-contract-performance"><thead><tr><th>Cliente / contrato</th><th>Status</th><th>Cargas</th><th>Volume no período</th><th>ATR médio</th><th>Entrega do contrato</th><th>Líquido</th><th>Entradas</th><th><span className="sr-only">Abrir</span></th></tr></thead><tbody>{data.contracts.slice(0,10).map(contract=>{const performance=contractPerformance.get(contract.id);return <tr key={contract.id}><td><strong>{contract.clientName}</strong><small>{contract.contractNumber||contract.title}</small></td><td><span className="summary-status-pill">{contract.status}</span></td><td>{contract.loadCount}</td><td>{decimalLabel(contract.loadedVolume)} t</td><td>{decimalLabel(performance?.averageAtr)} <small>kg/t</small></td><td>{performance?<><Progress value={performance.deliveryPercent}/><small>{decimalLabel(performance.totalLoadedVolume)} / {decimalLabel(performance.contractedVolume)} t</small></>:'—'}</td><td>{moneyLabel(contract.netAmount)}</td><td>{moneyLabel(contract.receivedAmount)}</td><td><ModuleLink aria-label={`Abrir contrato ${contract.contractNumber||contract.clientName}`} href={`/contratos?contrato=${contract.id}`}><ArrowUpRight size={18}/></ModuleLink></td></tr>;})}</tbody></table></div>:<div className="company-empty"><h3>Nenhum contrato cadastrado</h3><p>Cadastre um contrato para acompanhar os resultados da empresa.</p><ModuleLink className="btn" href="/contratos">Abrir contratos</ModuleLink></div>}</section>
   <p className="summary-footnote">Financeiro e produção usam as datas exatas do filtro. Entradas são classificadas pela data efetiva do caixa. Planejamento, manejo e cadastro agrícola representam o workspace; áreas cadastradas são um retrato atual.</p>
  </div>}
  {exporting&&data&&<SummaryExportDialog snapshot={{data,companyId:model.companyId}} onClose={()=>setExporting(false)}/>}
 </section>;
}

function ChangeBadge({value,label}:{value:string;label:string}){const amount=value===''?null:Number(value),Icon=amount===null||amount===0?Minus:amount>0?TrendingUp:TrendingDown;return <span className={`summary-change ${amount===null?'neutral':amount>=0?'positive':'negative'}`}><Icon size={13}/>{amount===null?'Sem base de comparação':`${amount>0?'+':''}${decimalLabel(amount)}%`} <small>{label}</small></span>}
function Metric({icon:Icon,label,value,detail,tone='default'}:{icon:typeof Banknote;label:string;value:string;detail:string;tone?:'default'|'warning'}){return <div className={tone==='warning'?'warning':''}><dt><span>{label}</span><i><Icon size={17}/></i></dt><dd>{value}</dd><small>{detail}</small></div>}
function ProgressCard({icon:Icon,title,percent,actual,target,detail}:{icon:typeof Sprout;title:string;percent:string;actual:string;target:string;detail:string}){const width=Math.max(0,Math.min(100,Number(percent)||0));return <article className="summary-panel summary-progress"><header><span><Icon size={18}/></span><div><small>PROGRESSO DE {title.toLocaleUpperCase('pt-BR')}</small><h3>{title}</h3></div><strong>{decimalLabel(percent)}%</strong></header><div className="summary-progress-track"><i style={{width:`${width}%`}}/></div><dl><div><dt>Realizado</dt><dd>{actual}</dd></div><div><dt>Meta</dt><dd>{target}</dd></div></dl><p>{detail}</p></article>}
