'use client';
import {useState} from 'react';
import {ArrowUpRight,ChevronLeft,ChevronRight,FileChartColumn,Filter} from 'lucide-react';
import {ModuleLink} from '@/shared/navigation/ModuleNavigation';
import {decimalLabel,moneyLabel} from '@/shared/utils/presentation';
import type {ExecutiveSummaryData} from '../types';
import {Progress} from './SummaryOperational';

export function SummaryContracts({data,onSelectContract,onSelectStatus,disabled}:{data:ExecutiveSummaryData;onSelectContract:(id:string)=>void;onSelectStatus:(status:string)=>void;disabled:boolean}){
 const [page,setPage]=useState(0),pageSize=10,pages=Math.ceil(data.contracts.length/pageSize),currentPage=Math.min(page,Math.max(0,pages-1)),rows=data.contracts.slice(currentPage*pageSize,(currentPage+1)*pageSize);
 const performance=new Map(data.contractPerformance?.map(item=>[item.id,item]));
 return <section id="summary-contracts" className="summary-block">
  <header className="summary-block-heading"><div><span className="summary-kicker"><FileChartColumn size={15}/>CONTRATOS E RESULTADOS</span><h3>Explore a carteira</h3><p>Analise um contrato para atualizar os indicadores e gráficos de toda a empresa.</p></div><div className="summary-statuses" aria-label="Filtrar pelo status atual">{data.contractStatus.map(item=><button type="button" key={item.status} disabled={disabled} aria-pressed={data.filters?.status===item.status} onClick={()=>onSelectStatus(data.filters?.status===item.status?'':item.status)}>{item.status}<strong>{item.count}</strong></button>)}</div></header>
  {rows.length?<><div className="summary-table-wrap" tabIndex={0} role="region" aria-label="Contratos e resultados da seleção"><table className="summary-table summary-contract-performance"><caption className="sr-only">Operação e valores no período; entrega acumulada de todo o contrato.</caption><thead><tr><th scope="col">Cliente / contrato</th><th scope="col">Status atual</th><th scope="col">Cargas</th><th scope="col">Volume<br/>No período</th><th scope="col">ATR médio<br/>No período</th><th scope="col">Entrega<br/>Acumulado do contrato</th><th scope="col">Líquido<br/>No período</th><th scope="col">Caixa<br/>No período</th><th scope="col">Explorar</th></tr></thead><tbody>{rows.map(contract=>{
   const item=performance.get(contract.id);
   return <tr key={contract.id}><th scope="row"><strong>{contract.clientName}</strong><small>{contract.contractNumber||contract.title}</small></th><td><span className="summary-status-pill">{contract.status}</span></td><td>{contract.loadCount}</td><td>{decimalLabel(contract.loadedVolume)} t</td><td>{decimalLabel(item?.averageAtr)} <small>kg/t</small></td><td>{item?<><Progress value={item.deliveryPercent}/><small>{decimalLabel(item.totalLoadedVolume)} / {decimalLabel(item.contractedVolume)} t</small></>:'—'}</td><td>{moneyLabel(contract.netAmount)}</td><td>{moneyLabel(contract.receivedAmount)}</td><td><div className="summary-contract-actions"><button type="button" className="summary-table-action" disabled={disabled} aria-label={`Analisar contrato ${contract.contractNumber||contract.title}`} onClick={()=>onSelectContract(contract.id)}><Filter size={13}/>Analisar</button><ModuleLink aria-label={`Abrir contrato ${contract.contractNumber||contract.title}`} href={`/contratos?contrato=${contract.id}`}><ArrowUpRight size={18}/></ModuleLink></div></td></tr>;
  })}</tbody></table></div><div className="summary-pagination"><span>{currentPage*pageSize+1}–{Math.min((currentPage+1)*pageSize,data.contracts.length)} de {data.contracts.length} contratos</span>{pages>1&&<div><button type="button" disabled={currentPage===0} aria-label="Página anterior de contratos" onClick={()=>setPage(currentPage-1)}><ChevronLeft size={16}/></button><span>Página {currentPage+1} de {pages}</span><button type="button" disabled={currentPage+1>=pages} aria-label="Próxima página de contratos" onClick={()=>setPage(currentPage+1)}><ChevronRight size={16}/></button></div>}</div></>:<div className="company-empty"><h3>Nenhum contrato nesta seleção</h3><p>Limpe os filtros para explorar a carteira da empresa.</p><ModuleLink className="btn" href="/contratos">Abrir contratos</ModuleLink></div>}
 </section>;
}
