import {useState} from 'react';
import {Ban,CalendarDays,ClipboardList,Plus,Truck} from 'lucide-react';
import {ModuleLink} from '@/shared/navigation/ModuleNavigation';
import {notifications,useConfirmation} from '@/shared/feedback';
import {dateLabel,decimalLabel,monthLabel} from '@/shared/utils/presentation';
import type {PlanningFieldLog,PlanningMutation,PlanningSnapshot} from '../types';

const kindLabel={planting:'Plantio',management:'Manejo',loss:'Perda / área morta'} as const;
function bulletinLabel(log:PlanningFieldLog){const details=log.details;return details?[details.operatorName&&`Operador: ${details.operatorName}`,details.equipmentCode&&`Equipamento: ${details.equipmentCode}`,details.startedAt&&details.endedAt&&`${details.startedAt}–${details.endedAt}`,details.materials.length&&`Materiais: ${details.materials.map(item=>item.description).join(', ')}`].filter(Boolean).join(' · '):'';}

export function PlanningDiary({data,fieldLogIds,harvestLoadIds,save,onNew}:{data:PlanningSnapshot;fieldLogIds:string[];harvestLoadIds:string[];save:(input:PlanningMutation)=>Promise<unknown>;onNew:()=>void}){
 const [view,setView]=useState<'day'|'month'>('day');const confirm=useConfirmation();
 const fieldLogs=data.fieldLogs.filter(item=>fieldLogIds.includes(item.id));const harvestLoads=data.harvestLoads.filter(item=>harvestLoadIds.includes(item.id));
 const voidLog=async(log:PlanningFieldLog)=>{const accepted=await confirm({title:'Anular este apontamento?',description:`O lançamento de ${decimalLabel(log.areaHa)} ha em ${log.plotName} será estornado. O registro continuará visível para auditoria.`,confirmLabel:'Anular apontamento',tone:'destructive'});if(!accepted)return;try{await save({action:'void-field-log',id:log.id,reason:'Apontamento anulado pelo usuário'});notifications.deleted('O apontamento foi anulado e os saldos foram recalculados.');}catch(caught){notifications.error((caught as Error).message);}};
 return <div className="planning-diary"><header className="planning-section-head"><div><h3>Diário da safra</h3><p>Registre o trabalho realizado em cada dia. Carregamentos aparecem automaticamente.</p></div><button className="btn company-primary" onClick={onNew}><Plus size={16}/>Novo apontamento</button></header>
  <section className="planning-diary-period-summary"><header><div><strong>Resumo do período</strong><span>{dateLabel(data.diaryPeriodSummary.dateFrom)} a {dateLabel(data.diaryPeriodSummary.dateTo)}</span></div><small>Totais calculados pelo sistema para o intervalo filtrado</small></header><div><article><span>Plantio</span><strong>{decimalLabel(data.diaryPeriodSummary.plantedAreaHa)} ha</strong></article><article><span>Manejo / tratos</span><strong>{decimalLabel(data.diaryPeriodSummary.managedAreaHa)} ha</strong></article><article><span>Perdas</span><strong>{decimalLabel(data.diaryPeriodSummary.lostAreaHa)} ha</strong></article><article className="accent"><span>Colheita</span><strong>{decimalLabel(data.diaryPeriodSummary.harvestedTons)} t</strong></article><article><span>Apontamentos</span><strong>{data.diaryPeriodSummary.fieldLogCount}</strong></article><article><span>Carregamentos</span><strong>{data.diaryPeriodSummary.loadCount}</strong></article></div></section>
  <div className="planning-diary-summary-head"><div className="planning-view-switch" role="group" aria-label="Agrupamento do resumo"><button className={view==='day'?'active':''} onClick={()=>setView('day')}>Por dia</button><button className={view==='month'?'active':''} onClick={()=>setView('month')}>Por mês</button></div><p>Valor realizado no {view==='day'?'dia':'mês'} e acumulado desde o início do intervalo.</p></div>
  <div className="planning-diary-summary"><table><thead><tr><th>{view==='day'?'Dia':'Mês'}</th><th>Plantio</th><th>Manejo</th><th>Perdas</th><th>Colheita</th><th>Carregamentos</th></tr></thead><tbody>{view==='day'?data.dailySummary.map(item=><tr key={item.date}><td><strong>{dateLabel(item.date)}</strong></td><td><strong>{decimalLabel(item.plantedAreaHa)} ha</strong><small>Acum. {decimalLabel(item.accumulatedPlantedAreaHa)} ha</small></td><td><strong>{decimalLabel(item.managedAreaHa)} ha</strong><small>Acum. {decimalLabel(item.accumulatedManagedAreaHa)} ha</small></td><td><strong>{decimalLabel(item.lostAreaHa)} ha</strong><small>Acum. {decimalLabel(item.accumulatedLostAreaHa)} ha</small></td><td><strong>{decimalLabel(item.harvestedTons)} t</strong><small>Acum. {decimalLabel(item.accumulatedHarvestedTons)} t</small></td><td><strong>{item.loadCount}</strong><small>Acum. {item.accumulatedLoadCount}</small></td></tr>):data.monthlySummary.map(item=><tr key={item.month}><td><strong>{monthLabel(item.month)}</strong></td><td><strong>{decimalLabel(item.plantedAreaHa)} ha</strong><small>Acum. {decimalLabel(item.accumulatedPlantedAreaHa)} ha</small></td><td><strong>{decimalLabel(item.managedAreaHa)} ha</strong><small>Acum. {decimalLabel(item.accumulatedManagedAreaHa)} ha</small></td><td><strong>{decimalLabel(item.lostAreaHa)} ha</strong><small>Acum. {decimalLabel(item.accumulatedLostAreaHa)} ha</small></td><td><strong>{decimalLabel(item.harvestedTons)} t</strong><small>Acum. {decimalLabel(item.accumulatedHarvestedTons)} t</small></td><td><strong>{item.loadCount}</strong><small>Acum. {item.accumulatedLoadCount}</small></td></tr>)}</tbody></table>{!(view==='day'?data.dailySummary:data.monthlySummary).length&&<div className="planning-inline-empty"><CalendarDays/>Nenhum movimento ativo no período selecionado.</div>}</div>
  <div className="planning-diary-columns"><section><header><span><ClipboardList/>Apontamentos de campo</span><small>{fieldLogs.filter(item=>!item.voidedAt).length} ativos nesta página</small></header>{fieldLogs.length?<div className="planning-log-list">{fieldLogs.map(log=>{const bulletin=bulletinLabel(log);return <article className={log.voidedAt?'voided':''} key={log.id}><div><span className={'planning-log-kind '+log.kind}>{kindLabel[log.kind]}</span><time>{dateLabel(log.occurredOn)}</time></div><strong>{log.farmName} · {log.plotName}</strong><p>{log.practiceName||log.notes||'Sem observações'} · {decimalLabel(log.areaHa)} ha</p>{bulletin&&<small className="planning-log-metadata">{bulletin}</small>}{log.voidedAt?<small>Anulado: {log.voidReason}</small>:<button className="icon-btn destructive" onClick={()=>void voidLog(log)} title="Anular apontamento" aria-label={'Anular apontamento de '+log.plotName}><Ban size={14}/></button>}</article>;})}</div>:<div className="planning-inline-empty">Nenhum apontamento de campo nesta página.</div>}</section><section><header><span><Truck/>Carregamentos da colheita</span><small>{harvestLoads.length} cargas nesta página</small></header>{harvestLoads.length?<div className="planning-log-list">{harvestLoads.map(load=><article key={load.id}><div><span className="planning-log-kind harvest">Colheita</span><time>{dateLabel(load.loadedAt)}</time></div><strong>{load.farmName} · {load.plotName}</strong><p>{decimalLabel(load.volumeTons)} t · contrato {load.contractNumber||'sem número'}</p><ModuleLink className="text-link" href={`/contratos?contrato=${encodeURIComponent(load.contractId)}&aba=loads`}>Abrir carregamento</ModuleLink></article>)}</div>:<div className="planning-inline-empty">Nenhum carregamento nesta página.</div>}</section></div>
 </div>;
}
