import {useState} from 'react';
import {ArrowRightLeft,ChevronDown,ChevronRight,ClipboardPlus,LandPlot,Leaf,MapPinned,Pencil,Plus,Search,Trash2} from 'lucide-react';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {ModuleLink} from '@/shared/navigation/ModuleNavigation';
import {notifications,useConfirmation} from '@/shared/feedback';
import {decimalLabel} from '@/shared/utils/presentation';
import {PlanningAllocationForm} from '../forms/PlanningAllocationForm';
import {ManagementSelectionForm,PlantedAreaForm,RemanagementForm} from '../forms/PlanningActionForms';
import type {PlanningAllocation,PlanningFarm,PlanningMutation,PlanningPlot,PlanningPractice} from '../types';

type DialogState=
 |{kind:'allocation';farm:PlanningFarm;plot:PlanningPlot}
 |{kind:'planted';farm:PlanningFarm;plot:PlanningPlot}
 |{kind:'remanejar';allocation:PlanningAllocation}
 |{kind:'management';allocation:PlanningAllocation}
 |null;

export function PlanningDistribution({periodId,farms,allFarms,practices,save,onNewLog}:{periodId:string;farms:PlanningFarm[];allFarms:PlanningFarm[];practices:PlanningPractice[];save:(input:PlanningMutation)=>Promise<unknown>;onNewLog:(plotId:string)=>void}){
 const [expanded,setExpanded]=useState<Set<string>>(()=>new Set());const [dialog,setDialog]=useState<DialogState>(null);const confirm=useConfirmation();
 const toggle=(id:string)=>setExpanded(current=>{const next=new Set(current);if(next.has(id))next.delete(id);else next.add(id);return next;});
 const cancel=async(allocation:PlanningAllocation)=>{const accepted=await confirm({title:'Cancelar esta distribuição?',description:`Os ${decimalLabel(allocation.areaHa)} ha de ${allocation.plotName} voltarão a ficar disponíveis. O histórico será preservado.`,confirmLabel:'Cancelar distribuição',tone:'destructive'});if(!accepted)return;try{await save({action:'cancel-allocation',id:allocation.id,expectedRevision:allocation.revision,reason:'Distribuição cancelada pelo usuário'});notifications.deleted('A distribuição foi cancelada e permaneceu no histórico.');}catch(caught){notifications.error((caught as Error).message);}};
 if(!allFarms.length)return <div className="company-empty"><span className="company-empty-icon"><LandPlot size={25}/></span><h3>Cadastre uma fazenda primeiro</h3><p>O plano precisa de fazendas e talhões para receber a distribuição.</p><ModuleLink className="btn company-primary" href="/cadastro?secao=fazenda">Ir para Fazendas</ModuleLink></div>;
 if(!farms.length)return <div className="company-empty"><span className="company-empty-icon"><Search size={25}/></span><h3>Nenhuma área encontrada</h3><p>Altere ou limpe o filtro para consultar as demais fazendas e talhões.</p></div>;
 return <><div className="planning-distribution-wrap"><table className="planning-distribution-table"><thead><tr><th>Fazenda</th><th>Área total</th><th>Plantada atual</th><th>Meta distribuída</th><th>Saldo a plantar</th><th>Projeção</th><th><span className="sr-only">Ações</span></th></tr></thead><tbody>{farms.map(farm=>{const open=expanded.has(farm.id);return <FarmRows key={farm.id} farm={farm} open={open} onToggle={()=>toggle(farm.id)} onDialog={setDialog} onCancel={cancel} onNewLog={onNewLog}/>;})}</tbody></table></div>
  <Dialog open={!!dialog} onOpenChange={value=>{if(!value)setDialog(null);}}><DialogContent className="form-modal planning-action-modal"><DialogHeader><DialogTitle>{dialog?.kind==='allocation'?(dialog.plot.allocation?'Editar distribuição':'Adicionar talhão ao plano'):dialog?.kind==='planted'?'Atualizar área plantada':dialog?.kind==='remanejar'?'Remanejar área':'Manejos da área'}</DialogTitle><DialogDescription>{dialog?.kind==='allocation'||dialog?.kind==='planted'?`${dialog.farm.name} · ${dialog.plot.name}`:dialog?.allocation?`${dialog.allocation.farmName} · ${dialog.allocation.plotName}`:'Planejamento'}</DialogDescription></DialogHeader>
   {dialog?.kind==='allocation'&&<PlanningAllocationForm plot={dialog.plot} allocation={dialog.plot.allocation??undefined} onClose={()=>setDialog(null)} onSave={async input=>{await save({action:'save-allocation',periodId,plotId:dialog.plot.id,input,id:dialog.plot.allocation?.id,expectedRevision:dialog.plot.allocation?.revision});if(dialog.plot.allocation)notifications.updated('A distribuição do talhão foi atualizada.');else notifications.created('O talhão foi adicionado ao plano.');}}/>}
   {dialog?.kind==='planted'&&<PlantedAreaForm plot={dialog.plot} onClose={()=>setDialog(null)} onSave={async(plantedAreaHa,reason)=>{await save({action:'set-planted',plotId:dialog.plot.id,plantedAreaHa,reason});notifications.saved('A área plantada atual foi registrada.');}}/>}
   {dialog?.kind==='remanejar'&&<RemanagementForm allocation={dialog.allocation} farms={allFarms} onClose={()=>setDialog(null)} onSave={async(targetPlotId,areaHa,reason)=>{await save({action:'remanejar',allocationId:dialog.allocation.id,targetPlotId,areaHa,reason,expectedRevision:dialog.allocation.revision});notifications.saved('A área foi remanejada e o histórico foi preservado.');}}/>}
   {dialog?.kind==='management'&&<ManagementSelectionForm allocation={dialog.allocation} practices={practices} onClose={()=>setDialog(null)} onSave={async practiceIds=>{await save({action:'set-practices',allocationId:dialog.allocation.id,practiceIds,expectedRevision:dialog.allocation.revision});notifications.saved('Os manejos da área foram atualizados.');}}/>}
  </DialogContent></Dialog>
 </>;
}

function FarmRows({farm,open,onToggle,onDialog,onCancel,onNewLog}:{farm:PlanningFarm;open:boolean;onToggle:()=>void;onDialog:(value:DialogState)=>void;onCancel:(allocation:PlanningAllocation)=>Promise<void>;onNewLog:(plotId:string)=>void}){
 const projected=Number(farm.plantedAreaHa)+Number(farm.remainingPlannedAreaHa);
 return <>
  <tr className={'planning-farm-row '+(open?'open':'')}><td><button onClick={onToggle} className="planning-farm-toggle" aria-expanded={open}>{open?<ChevronDown/>:<ChevronRight/>}<span><strong>{farm.name}</strong><small>{farm.city} / {farm.state} · {farm.plots.length} talh{farm.plots.length===1?'ão':'ões'}</small></span></button></td><td>{decimalLabel(farm.totalAreaHa)} ha</td><td>{decimalLabel(farm.plantedAreaHa)} ha</td><td className="planning-positive">{decimalLabel(farm.plannedAreaHa)} ha</td><td>{decimalLabel(farm.remainingPlannedAreaHa)} ha</td><td>{decimalLabel(projected)} ha</td><td><button className="icon-btn" onClick={onToggle} aria-label={open?'Recolher talhões':'Mostrar talhões'}>{open?<ChevronDown/>:<ChevronRight/>}</button></td></tr>
  {open&&<tr className="planning-plots-row"><td colSpan={7}><div className="planning-plots-panel"><header><div><h3>Talhões de {farm.name}</h3><p>Clique no nome do talhão para lançar plantio, manejo ou perda no Diário.</p></div><ModuleLink className="btn" href={`/cadastro?secao=fazenda&fazenda=${encodeURIComponent(farm.id)}`}><Plus size={15}/>Cadastrar ou alterar talhão</ModuleLink></header>{!farm.plots.length?<div className="planning-inline-empty">Cadastre um talhão para distribuir a área do plano.</div>:<table><thead><tr><th>Talhão</th><th>Área física</th><th>Plantada atual</th><th>Meta da safra</th><th>Realizado</th><th>Saldo a plantar</th><th>Ações</th></tr></thead><tbody>{farm.plots.map(plot=><tr key={plot.id}><td><button className="planning-plot-open" onClick={()=>onNewLog(plot.id)}><strong>{plot.name}</strong><small>Lançar atividade</small></button></td><td>{decimalLabel(plot.areaHa)} ha</td><td>{decimalLabel(plot.plantedAreaHa)} ha</td><td className={plot.allocation?'planning-positive':''}>{decimalLabel(plot.allocation?.areaHa??'0')} ha</td><td>{decimalLabel(plot.allocation?.executedAreaHa??'0')} ha</td><td>{decimalLabel(plot.allocation?.remainingExecutionAreaHa??'0')} ha</td><td><div className="planning-row-actions"><button className="btn planning-log-button" onClick={()=>onNewLog(plot.id)}><ClipboardPlus/>Lançar dia</button><button className="icon-btn" onClick={()=>onDialog({kind:'planted',farm,plot})} title="Corrigir área plantada atual" aria-label={'Corrigir área plantada de '+plot.name}><MapPinned/></button>{plot.allocation?<><button className="icon-btn" onClick={()=>onDialog({kind:'allocation',farm,plot})} title="Editar meta distribuída" aria-label={'Editar distribuição de '+plot.name}><Pencil/></button><button className="icon-btn" onClick={()=>onDialog({kind:'management',allocation:plot.allocation!})} title="Planejar manejos" aria-label={'Planejar manejos de '+plot.name}><Leaf/></button><button className="icon-btn" onClick={()=>onDialog({kind:'remanejar',allocation:plot.allocation!})} title="Remanejar saldo" aria-label={'Remanejar '+plot.name}><ArrowRightLeft/></button><button className="icon-btn destructive" onClick={()=>void onCancel(plot.allocation!)} title="Cancelar distribuição" aria-label={'Cancelar distribuição de '+plot.name}><Trash2/></button></>:Number(plot.maxAllocationAreaHa)>0&&<button className="btn planning-add-area" onClick={()=>onDialog({kind:'allocation',farm,plot})}><Plus size={14}/>Planejar área</button>}</div></td></tr>)}</tbody></table>}</div></td></tr>}
 </>;
}
