import {ArrowRight,CalendarRange,Pencil,Search} from 'lucide-react';
import {dateLabel,decimalLabel} from '@/shared/utils/presentation';
import type {PlanningPeriod} from '../types';

const statusLabel={active:'Ativa',completed:'Concluída',cancelled:'Cancelada'} as const;

export function PlanningPlans({periods,hasPeriods,onSelect,onEdit}:{periods:PlanningPeriod[];hasPeriods:boolean;onSelect:(id:string)=>void;onEdit:(period:PlanningPeriod)=>void}){
 if(!periods.length)return hasPeriods?<div className="company-empty"><span className="company-empty-icon"><Search size={25}/></span><h3>Nenhuma safra encontrada</h3><p>Altere ou limpe o filtro para consultar as demais safras.</p></div>:<div className="company-empty"><span className="company-empty-icon"><CalendarRange size={25}/></span><h3>Crie a primeira safra</h3><p>Defina o período e a meta de plantio. Depois abra a safra para distribuir áreas, lançar o Diário e configurar a colheita.</p></div>;
 return <div className="planning-season-table"><table><thead><tr><th>Safra / plano</th><th>Período</th><th>Plantado nesta safra</th><th>Meta de plantio</th><th>Meta de colheita</th><th>Situação</th><th><span className="sr-only">Ações</span></th></tr></thead><tbody>{periods.map(period=><tr key={period.id}><td><button className="planning-season-name" onClick={()=>onSelect(period.id)}><strong>{period.name}</strong><small>{period.cultureName} · {period.cultureSubtypeName}</small></button></td><td>{dateLabel(period.startDate)}<small>até {dateLabel(period.endDate)}</small></td><td><strong>{decimalLabel(period.plantedExecutedAreaHa)} ha</strong><small>{decimalLabel(period.plantingRemainingAreaHa)} ha restantes</small></td><td>{decimalLabel(period.targetAreaHa)} ha<small>{decimalLabel(period.allocatedAreaHa)} ha distribuídos</small></td><td>{decimalLabel(period.harvestTargetTons)} t<small>{decimalLabel(period.harvestActualTons)} t carregadas</small></td><td><span className={'planning-period-status '+period.status}>{statusLabel[period.status]}</span></td><td><div className="planning-row-actions"><button className="icon-btn" onClick={()=>onEdit(period)} title="Editar safra" aria-label={'Editar '+period.name}><Pencil/></button><button className="btn planning-open-season" onClick={()=>onSelect(period.id)}>Abrir<ArrowRight size={14}/></button></div></td></tr>)}</tbody></table></div>;
}
