-- A new quotation receives its database id inside the existing quotation RPC.
-- Keep the upload under a unique draft object path, then link it to the row
-- returned by that RPC in the same transaction.
ALTER TABLE public.billing_quotations
 DROP CONSTRAINT billing_quotations_attachment;
ALTER TABLE public.billing_quotations
 ADD CONSTRAINT billing_quotations_attachment CHECK(
  (attachment_key IS NULL AND attachment_name='' AND attachment_size IS NULL)
  OR (
   attachment_key IS NOT NULL
   AND length(attachment_key)<=500
   AND attachment_key LIKE owner_id::text || '/quotations/%.pdf'
   AND length(btrim(attachment_name)) BETWEEN 1 AND 255
   AND attachment_size BETWEEN 1 AND 10485760
  )
 );

ALTER FUNCTION billing_private.quotations_dispatch(text,text,jsonb)
 RENAME TO quotations_dispatch_before_pdf_create_flow;
REVOKE ALL ON FUNCTION billing_private.quotations_dispatch_before_pdf_create_flow(
 text,text,jsonb
) FROM PUBLIC,anon,authenticated;

CREATE FUNCTION billing_private.quotations_dispatch(
 p_resource text,p_action text,p_payload jsonb
) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE
 v_owner uuid:=billing_private.current_owner_id();
 v_quote_id uuid;
 v_attachment_key text;
 v_attachment_name text;
 v_attachment_size bigint;
 v_result jsonb;
 v_quote public.billing_quotations;
BEGIN
 IF p_resource<>'quotations' OR p_action<>'save'
  OR NOT (
   p_payload ? 'attachmentKey'
   OR p_payload ? 'attachmentName'
   OR p_payload ? 'attachmentSize'
  ) THEN
  RETURN billing_private.quotations_dispatch_before_pdf_create_flow(
   p_resource,p_action,p_payload
  );
 END IF;
 IF v_owner IS NULL OR auth.uid() IS NULL THEN
  RAISE EXCEPTION 'Faça login para acessar o sistema.' USING ERRCODE='28000';
 END IF;
 IF p_payload IS NULL OR jsonb_typeof(p_payload)<>'object'
  OR jsonb_typeof(p_payload->'attachmentKey') IS DISTINCT FROM 'string'
  OR jsonb_typeof(p_payload->'attachmentName') IS DISTINCT FROM 'string'
  OR jsonb_typeof(p_payload->'attachmentSize') IS DISTINCT FROM 'number' THEN
  RAISE EXCEPTION 'Selecione um arquivo PDF válido.' USING ERRCODE='22023';
 END IF;

 PERFORM billing_private.lock_request_actor();
 v_owner=billing_private.current_owner_id();
 PERFORM billing_private.authorize('quotations.write');
 v_attachment_key=btrim(p_payload->>'attachmentKey');
 v_attachment_name=btrim(p_payload->>'attachmentName');
 v_attachment_size=(p_payload->>'attachmentSize')::bigint;
 IF length(v_attachment_key)>500
  OR length(v_attachment_name) NOT BETWEEN 1 AND 255
  OR v_attachment_size NOT BETWEEN 1 AND 10485760
  OR v_attachment_key NOT LIKE v_owner::text || '/quotations/%.pdf'
  OR NOT EXISTS(
   SELECT 1 FROM storage.objects o
   WHERE o.bucket_id='billing-quotation-files' AND o.name=v_attachment_key
  ) THEN
  RAISE EXCEPTION 'Envie um arquivo PDF válido para este espaço antes de salvar.'
   USING ERRCODE='23514';
 END IF;

 v_result=billing_private.quotations_dispatch_before_pdf_create_flow(
  p_resource,p_action,
  p_payload-ARRAY['attachmentKey','attachmentName','attachmentSize']
 );
 v_quote_id=nullif(v_result->'quote'->>'id','')::uuid;
 UPDATE public.billing_quotations q SET
  attachment_key=v_attachment_key,
  attachment_name=v_attachment_name,
  attachment_size=v_attachment_size
 WHERE q.owner_id=v_owner AND q.id=v_quote_id
 RETURNING * INTO v_quote;
 IF NOT FOUND THEN
  RAISE EXCEPTION 'Cotação não encontrada.' USING ERRCODE='P0002';
 END IF;
 RETURN jsonb_set(
  v_result,'{quote}',billing_private.quotation_json(v_quote),false
 );
EXCEPTION
 WHEN invalid_text_representation OR numeric_value_out_of_range THEN
  RAISE EXCEPTION 'Selecione um arquivo PDF válido.' USING ERRCODE='22023';
END $$;
REVOKE ALL ON FUNCTION billing_private.quotations_dispatch(text,text,jsonb)
 FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION billing_private.quotations_dispatch(text,text,jsonb)
 TO authenticated;

COMMENT ON FUNCTION billing_private.quotations_dispatch(text,text,jsonb) IS
 'Routes quotations and links an optional private draft PDF to the id generated by the existing save transaction.';
