import {useEffect,useRef,useState} from 'react';
import {FileText,CalendarDays,Loader2,Save,Users,Plus} from 'lucide-react';
import {Field,Choice} from '@/shared/components/Common';
import {Textarea} from '@/components/ui/textarea';
import {ModuleLink,useModuleNavigation} from '@/shared/navigation/ModuleNavigation';
import {notifications} from '@/shared/feedback';
import {formatCnpj} from '@/shared/utils/cnpj';
import {useContractOptions} from '../hooks/useContractOptions';
import {contractStatuses,type BillingContract,type ContractAtrPeriodType,type ContractAtrPriceType,type ContractInput} from '../types';
import {useContractsMutation} from '../hooks/useContracts';
import {contractHref,contractsHref} from '../utils/contractFormat';
import {ContractLoadState} from '../components/ContractLoadState';
export function ContractForm({contract,onBusy}:{contract?:BillingContract;onBusy?:(busy:boolean)=>void}){
 const mutation=useContractsMutation();
 const m=useContractOptions(),{navigate}=useModuleNavigation();const [data,setData]=useState<ContractInput>(contract?{title:contract.title,contractNumber:contract.contractNumber,companyId:contract.companyId,clientId:contract.clientId,typeId:contract.typeId,status:contract.status,startDate:contract.startDate,endDate:contract.endDate,contractedVolume:contract.contractedVolume.replace('.',','),atrPriceType:contract.atrPriceType,atrPeriodType:contract.atrPeriodType,value:contract.value.replace('.',','),notes:contract.notes}:{title:'',contractNumber:'',companyId:'',clientId:'',typeId:'',status:'Ativo',startDate:'',endDate:'',contractedVolume:'',atrPriceType:'gross',atrPeriodType:'monthly',value:'',notes:''});
 const[saving,setSaving]=useState(false),[error,setError]=useState('');const mounted=useRef(true),inFlight=useRef(false);useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 useEffect(()=>{onBusy?.(saving);return()=>onBusy?.(false);},[saving,onBusy]);
 const set=(key:keyof ContractInput,value:string)=>setData(d=>({...d,[key]:value}));
 const cancel=contract?contractHref(contract.id):contractsHref;
 if(m.loading||m.error)return <ContractLoadState {...m} onRetry={m.reload}/>;
 if(!m.companies.length||!m.clients.length||!m.types.length)return <div className="company-empty"><span className="company-empty-icon"><Users size={25}/></span><h3>Prepare os cadastros do contrato</h3><p>Você precisa de uma empresa, um cliente e um tipo de contrato cadastrados para continuar.</p><div className="contract-type-suggestions">{!m.companies.length&&<ModuleLink className="btn company-primary" href="/configuracoes?secao=empresas">Cadastrar empresa</ModuleLink>}{!m.clients.length&&<ModuleLink className="btn company-primary" href="/cadastro?secao=clientes&novo=1"><Plus size={15}/>Cadastrar cliente</ModuleLink>}{!m.types.length&&<ModuleLink className="btn" href="/cadastro?secao=contratos&novo=1"><Plus size={15}/>Cadastrar tipo de contrato</ModuleLink>}</div></div>;
 return <form onSubmit={async e=>{e.preventDefault();if(inFlight.current)return;setError('');try{inFlight.current=true;setSaving(true);const saved=await mutation.mutateAsync({input:{...data,companyId:m.activeCompany?.id??''},id:contract?.id});if(mounted.current){if(contract)notifications.updated('O contrato foi atualizado.');else notifications.created('O contrato foi cadastrado.');navigate(contractHref(saved.id),{replace:true});}}catch(e){if(mounted.current){const message=(e as Error).message;setError(message);notifications.error(message);}}finally{inFlight.current=false;if(mounted.current)setSaving(false);}}}>
 <div className="client-form billing-form contract-editor-single"><fieldset className="company-fieldset" disabled={saving}><section className="client-form-section"><h3><FileText size={17}/>Dados do contrato</h3><p className="field-help">Este contrato pertence a <strong>{m.activeCompany?.name}</strong>.</p><Field label="Nome do contrato *"><input required maxLength={150} value={data.title} onChange={e=>set('title',e.target.value)} placeholder="Ex.: Serviços agrícolas — Safra 2026/2027"/></Field><Field label="Número do contrato (opcional)"><input maxLength={100} value={data.contractNumber} onChange={e=>set('contractNumber',e.target.value)} placeholder="Ex.: 123/2026"/></Field><Field label="Cliente *"><Choice label="Selecione o cliente" value={data.clientId} onChange={v=>set('clientId',v)} items={m.clients.map(c=>({value:c.id,label:c.legalName,description:'CNPJ: '+formatCnpj(c.cnpj)}))}/></Field><Field label="Tipo de contrato *"><Choice label="Selecione o tipo de contrato" value={data.typeId} onChange={v=>set('typeId',v)} items={m.types.map(t=>({value:t.id,label:t.name}))}/></Field></section>
 <section className="client-form-section"><h3><CalendarDays size={17}/>Período e condições</h3><div className="form-grid"><Field label="Data do contrato *"><input required type="date" min="1900-01-01" max="9999-12-31" value={data.startDate} onChange={e=>set('startDate',e.target.value)}/></Field><Field label="Data final"><input type="date" min={data.startDate||'1900-01-01'} max="9999-12-31" value={data.endDate} onChange={e=>set('endDate',e.target.value)}/></Field></div><div className="form-grid"><Field label="Quantidade contratada (t) *"><input required inputMode="decimal" maxLength={18} value={data.contractedVolume} placeholder="0,000" onChange={e=>set('contractedVolume',e.target.value)}/></Field><Field label="Situação *"><Choice label="Situação" value={data.status} onChange={v=>set('status',v)} items={contractStatuses.map(value=>({value,label:value}))}/></Field></div><div className="form-grid"><Field label="Valor do ATR *"><Choice label="Valor do ATR" value={data.atrPriceType} onChange={v=>set('atrPriceType',v as ContractAtrPriceType)} items={[{value:'gross',label:'Bruto'},{value:'net',label:'Líquido'}]}/></Field><Field label="Período do ATR *"><Choice label="Período do ATR" value={data.atrPeriodType} onChange={v=>set('atrPeriodType',v as ContractAtrPeriodType)} items={[{value:'monthly',label:'Mensal'},{value:'accumulated',label:'Acumulado'}]}/></Field></div><p className="field-help">O faturamento é a quantidade × ATR medido do carregamento × cotação escolhida do mês anterior. A mesma referência de cotação vale durante todo o mês.</p><Field label="Observações"><Textarea rows={4} maxLength={4000} value={data.notes} onChange={e=>set('notes',e.target.value)} placeholder="Informações adicionais sobre o contrato"/></Field><p className="field-help">* Campos obrigatórios. Data final e observações podem ser preenchidas depois.</p></section></fieldset>
 {error&&<p className="form-error" role="alert">{error}</p>}<div className="form-actions"><button type="button" className="btn" disabled={saving} onClick={()=>navigate(cancel)}>Cancelar</button><button type="submit" className="btn company-primary" disabled={saving}>{saving?<Loader2 size={16} className="animate-spin"/>:<Save size={16}/>} {saving?'Salvando…':'Salvar contrato'}</button></div></div></form>;
}
