"use client";
import {useEffect,useState} from "react";import {ModuleLink as Link,ModuleNavigationProvider,useModuleNavigation} from "@/shared/navigation/ModuleNavigation";import {Home,Users,FileText,ChartNoAxesCombined,CalendarDays,CalendarRange,Settings,Search,ChevronRight,ReceiptText,FileChartColumn} from "lucide-react";
import {SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarMenuSub,SidebarMenuSubItem,SidebarMenuSubButton,SidebarTrigger,useSidebar} from "@/components/ui/sidebar";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";import {Command,CommandInput,CommandList,CommandEmpty,CommandGroup,CommandItem} from "@/components/ui/command";
import {useApp} from "@/shared/state/AppProvider";import {initials} from "@/shared/utils/format";import {InicioPage} from "@/modules/inicio/components/InicioPage";import {CadastroPage} from "@/modules/cadastro/components/CadastroPage";import {ContratosPage} from "@/modules/contratos/components/ContratosPage";import {ResumoPage} from "@/modules/resumo/components/ResumoPage";import {AgendaPage} from "@/modules/agenda/components/AgendaPage";import {ConfiguracoesPage} from "@/modules/configuracoes/components/ConfiguracoesPage";
import {SessionButton} from "@/shared/supabase/SessionButton";
import {cadastroSections} from "@/modules/cadastro/sections";
import {configuracoesSections} from "@/modules/configuracoes/sections";
import {RelatoriosPage} from "@/modules/relatorios/components/RelatoriosPage";
import {PlanejamentoPage} from "@/modules/planejamento/components/PlanejamentoPage";
import {Choice} from "@/shared/components/Common";
import {useWorkspaceCompany} from "@/shared/state/WorkspaceCompanyProvider";
const modules=[{path:"/",name:"Início",icon:Home,component:InicioPage},{path:"/cadastro",name:"Cadastros",icon:Users,component:CadastroPage},{path:"/contratos",name:"Contratos",icon:FileText,component:ContratosPage},{path:"/planejamento",name:"Planejamento",icon:CalendarRange,component:PlanejamentoPage},{path:"/resumo",name:"Resumo",icon:ChartNoAxesCombined,component:ResumoPage},{path:"/agenda",name:"Agenda",icon:CalendarDays,component:AgendaPage},{path:"/relatorios",name:"Relatórios",icon:FileChartColumn,component:RelatoriosPage},{path:"/configuracoes",name:"Configurações",icon:Settings,component:ConfiguracoesPage}];
function Navigation(){const{pathname:path,searchParams}=useModuleNavigation();const selectedCadastro=path==="/cadastro"?(cadastroSections.find(s=>s.id===searchParams.get("secao"))??cadastroSections[0]):undefined;const[cadastroState,setCadastroState]=useState({path,open:path==="/cadastro"});const cadastroOpen=cadastroState.path===path?cadastroState.open:path==="/cadastro";const m=useApp();const{setOpenMobile}=useSidebar();return <Sidebar className="app-sidebar"><SidebarHeader className="brand-header"><Link href="/" className="brand"><span className="brand-mark" aria-hidden="true"><ReceiptText size={23} strokeWidth={1.7}/></span><span className="system-brand">Controle de<br/>Faturamento</span></Link><span className="brand-caption"></span></SidebarHeader><SidebarContent><div className="nav-label">PRINCIPAL</div><SidebarMenu className="main-nav">{modules.filter(x=>x.path!=="/configuracoes").map(x=><SidebarMenuItem key={x.path}><SidebarMenuButton asChild={x.path!=="/cadastro"} type={x.path==="/cadastro"?"button":undefined} isActive={path===x.path&&(x.path==="/cadastro"||(!selectedCadastro))} className="nav-item" aria-expanded={x.path==="/cadastro"?cadastroOpen:undefined} onClick={x.path==="/cadastro"?()=>setCadastroState({path,open:!cadastroOpen}):undefined}>{x.path==="/cadastro"?<><x.icon/><span>{x.name}</span><ChevronRight className={"cadastro-toggle-chevron "+(cadastroOpen?"expanded":"")} aria-hidden="true"/></>:<Link href={x.path} aria-current={path===x.path&&!selectedCadastro?"page":undefined} onClick={()=>setOpenMobile(false)}><x.icon/><span>{x.name}</span></Link>}</SidebarMenuButton>{x.path==="/cadastro"&&cadastroOpen&&<SidebarMenuSub className="cadastro-subnav" aria-label="Submódulos de Cadastros">{cadastroSections.map(section=><SidebarMenuSubItem key={section.id}><SidebarMenuSubButton asChild isActive={selectedCadastro?.id===section.id} className="cadastro-subnav-link"><Link href={section.href} aria-current={selectedCadastro?.id===section.id?"page":undefined} onClick={()=>setOpenMobile(false)}><section.icon/><span>{section.name}</span></Link></SidebarMenuSubButton></SidebarMenuSubItem>)}</SidebarMenuSub>}</SidebarMenuItem>)}</SidebarMenu><div className="nav-label management-label">GERENCIAMENTO</div><SidebarMenu className="main-nav"><SidebarMenuItem><SidebarMenuButton asChild isActive={path==="/configuracoes"} className="nav-item"><Link href="/configuracoes" aria-current={path==="/configuracoes"?"page":undefined} onClick={()=>setOpenMobile(false)}><Settings/><span>Configurações</span></Link></SidebarMenuButton></SidebarMenuItem></SidebarMenu></SidebarContent><SidebarFooter className="sidebar-bottom"><Link href="/configuracoes?secao=perfil" className="user-profile"><span className="user-avatar">{initials(m.settings.name)}</span><div><strong>{m.settings.name}</strong><small>Minha conta</small></div><ChevronRight size={16}/></Link></SidebarFooter></Sidebar>}
export function AppShell({initialHref="/"}:{initialHref?:string}){return <ModuleNavigationProvider initialHref={initialHref}><WorkspaceShell/></ModuleNavigationProvider>}
function WorkspaceShell(){const{pathname:path,searchParams,navigate}=useModuleNavigation();const selectedCadastro=path==="/cadastro"?(cadastroSections.find(s=>s.id===searchParams.get("secao"))??cadastroSections[0]):undefined;const selectedConfiguracao=path==="/configuracoes"?configuracoesSections.find(s=>s.id===searchParams.get("secao")):undefined;const m=useApp();const workspace=useWorkspaceCompany();const[search,setSearch]=useState(false);const current=modules.find(x=>x.path===path);const Page=current?.component;useEffect(()=>{const handler=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key==="k"){e.preventDefault();setSearch(x=>!x)}};window.addEventListener("keydown",handler);return()=>window.removeEventListener("keydown",handler)},[]);
function go(url:string){setSearch(false);navigate(url)}return <SidebarProvider style={{"--sidebar-width":"244px"} as React.CSSProperties}><Navigation/><div className={"app-main "+(m.settings.compact?"compact":"")}><header className="topbar"><div className="breadcrumbs"><SidebarTrigger aria-label="Alternar menu lateral" className="sidebar-toggle"/><span className="breadcrumb-home">Espaço de trabalho</span><ChevronRight size={14}/><strong>{selectedCadastro?"Cadastros / "+selectedCadastro.name:selectedConfiguracao?"Configurações / "+selectedConfiguracao.title:current?.name||"Página"}</strong></div>{workspace.companies.length>1&&<div className="top-company-switch"><span>Empresa</span><Choice label="Alterar empresa ativa" value={workspace.activeCompanyId} onChange={workspace.selectCompany} items={workspace.companies.map(company=>({value:company.id,label:company.name}))}/></div>}<button className="global-search" onClick={()=>setSearch(true)}><Search size={17}/><span>Buscar em todo o sistema...</span><kbd>⌘ K</kbd></button><Link href="/configuracoes?secao=perfil" className="top-avatar" aria-label="Meu perfil">{initials(m.settings.name)}</Link><SessionButton/></header><main className="page-content">{Page?<Page key={(current?.path??'')+':'+workspace.activeCompanyId}/>:<div className="empty"><h1>Página não encontrada</h1><Link href="/" className="text-link">Voltar ao início</Link></div>}<footer className="page-footer"><span>Controle de Faturamento</span></footer></main></div><Dialog open={search} onOpenChange={setSearch}><DialogContent className="search-modal"><DialogTitle className="sr-only">Busca global</DialogTitle><DialogDescription className="sr-only">Encontre e abra os módulos do sistema.</DialogDescription><Command><CommandInput placeholder="O que você procura?"/><CommandList><CommandEmpty>Nenhum resultado encontrado.</CommandEmpty><CommandGroup heading="Módulos">{modules.map(x=><CommandItem key={x.path} onSelect={()=>go(x.path)}><x.icon/>{x.name}</CommandItem>)}</CommandGroup><CommandGroup heading="Cadastros">{cadastroSections.map(section=><CommandItem key={section.id} value={"Cadastros "+section.name} onSelect={()=>go(section.href)}><section.icon/>{section.name}</CommandItem>)}</CommandGroup><CommandGroup heading="Configurações">{configuracoesSections.map(section=><CommandItem key={section.id} value={"Configurações "+section.title} onSelect={()=>go("/configuracoes?secao="+section.id)}><section.icon/>{section.title}</CommandItem>)}</CommandGroup></CommandList></Command></DialogContent></Dialog></SidebarProvider>}
