"use client";
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from "@/components/ui/select";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Search} from "lucide-react";
type ChoiceItem={value:string;label:string;description?:string};
export function Choice({value,onChange,items,label,disabled=false}:{value:string;onChange:(v:string)=>void;items:ChoiceItem[];label:string;disabled?:boolean}){const selected=items.find(item=>item.value===value),twoLines=items.some(item=>item.description);return <Select value={value} onValueChange={onChange} disabled={disabled}><SelectTrigger aria-label={label} className={'choice'+(twoLines?' choice-two-lines':'')}>{selected?.description?<span className="choice-value-two-lines"><span>{selected.label}</span><small>{selected.description}</small></span>:<SelectValue placeholder={label}/>}</SelectTrigger><SelectContent className={twoLines?'choice-content-two-lines':undefined}>{items.map(i=><SelectItem key={i.value} value={i.value} textValue={i.description?i.label+' '+i.description:i.label} className={i.description?'choice-item-two-lines':undefined}>{i.description?<span className="choice-option-two-lines"><span>{i.label}</span><small>{i.description}</small></span>:i.label}</SelectItem>)}</SelectContent></Select>}
export function Modal({open,onClose,title,children}:{open:boolean;onClose:()=>void;title:string;children:React.ReactNode}){return <Dialog open={open} onOpenChange={v=>{if(!v)onClose()}}><DialogContent className="form-modal"><DialogHeader><DialogTitle>{title}</DialogTitle><DialogDescription>Ambiente de demonstração. Alterações válidas nesta sessão.</DialogDescription></DialogHeader>{children}</DialogContent></Dialog>}
export function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
export function Badge({status}:{status:string}){return <span className={"status status-"+status.toLowerCase().replace(/\s/g,"-")}>{status}</span>}
export function LocalSearch({value,onChange,placeholder}:{value:string;onChange:(v:string)=>void;placeholder:string}){return <div className="local-search"><Search size={17}/><input aria-label={placeholder} placeholder={placeholder} value={value} onChange={e=>onChange(e.target.value)}/></div>}
export function Empty({text="Nenhum resultado encontrado."}:{text?:string}){return <div className="empty">{text}</div>}
